var responseExample = {
	dayIndexExample:
		[
			[
				[ 'Peru', '20' ],
				[ 'Argentinië', '20' ],
				[ 'Republiek van Argentinië', '20' ],
				[ 'Chili', '20' ],
				[ 'Republiek van Piratini', '20' ],
				[ 'Ecuador', '20' ],
				[ 'Bolivia', '20' ],
				[ 'Frans Algerije', '20' ],
				[ 'Brits Egypte', '20' ],
				[ 'Frans West-Afrika', '20' ],
				[ 'Abessinië', '20' ],
				[ 'Anglo-Egyptisch Soedan', '20' ],
				[ 'Unie van Zuid-Afrika', '20' ],
				[ 'Belgisch Congo', '20' ],
				[ 'Duits Kameroen', '20' ],
				[ 'Duits Namibië', '20' ]
			],
			[
				[ 'Republiek van Australië', '21' ],
				[ 'Nederlands Oost-Indië', '21' ],
				[ 'Het Duitse Rijk', '20' ],
				[ 'Griekenland', '20' ],
				[ 'Brits Canada', '20' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '20' ],
				[ 'Caribische Eilandenrepubliek', '20' ],
				[ 'Frans Algerije', '20' ],
				[ 'Unie van Zuid-Afrika', '20' ],
				[ 'Duits Kameroen', '20' ],
				[ 'Portugees Mozambique', '20' ],
				[ 'Frans Madagascar', '20' ],
				[ 'Republiek Opper Volta', '20' ],
				[ 'Yakutia', '20' ],
				[ 'Frankrijk', '19' ],
				[ 'Oostenrijk-Hongarije', '19' ]
			],
			[
				[ 'Argentinië', '32' ],
				[ 'Japanse rijk', '31' ],
				[ 'Belgisch Congo', '26' ],
				[ 'Republiek Opper Volta', '26' ],
				[ 'Het Koninkrijk Engeland', '25' ],
				[ 'Arabië', '25' ],
				[ 'Kazachstan', '24' ],
				[ 'Frans Algerije', '23' ],
				[ 'Frankrijk', '21' ],
				[ 'Het Duitse Rijk', '21' ],
				[ 'Italië', '21' ],
				[ 'Verenigde Staten van Amerika', '21' ],
				[ 'Abessinië', '21' ],
				[ 'Duits Namibië', '21' ],
				[ 'Koreaanse Rijk', '21' ],
				[ 'Australië', '21' ]
			],
			[
				[ 'Het Duitse Rijk', '27' ],
				[ 'Het Koninkrijk Engeland', '27' ],
				[ 'Italië', '27' ],
				[ 'Zweden', '26' ],
				[ 'Belgisch Congo', '26' ],
				[ 'Duits Namibië', '26' ],
				[ 'Frankrijk', '25' ],
				[ 'Frans Algerije', '25' ],
				[ 'Unie van Zuid-Afrika', '25' ],
				[ 'Nederlands Oost-Indië', '25' ],
				[ 'Arabië', '24' ],
				[ 'Republiek China', '23' ],
				[ 'Baffin', '21' ],
				[ 'Republiek van Argentinië', '21' ],
				[ 'Ecuador', '21' ],
				[ 'Brits Egypte', '21' ]
			],
			[
				[ 'Duits Namibië', '32' ],
				[ 'Brits Birma', '32' ],
				[ 'Frankrijk', '31' ],
				[ 'Republiek Opper Volta', '31' ],
				[ 'Het Duitse Rijk', '29' ],
				[ 'Het Koninkrijk Engeland', '29' ],
				[ 'Japanse rijk', '29' ],
				[ 'Frans Algerije', '28' ],
				[ 'Zweden', '27' ],
				[ 'Belgisch Congo', '27' ],
				[ 'Republiek China', '27' ],
				[ 'Verenigde Staten van Amerika', '26' ],
				[ 'Venezuela', '26' ],
				[ 'Arabië', '26' ],
				[ 'Nederlands Oost-Indië', '26' ],
				[ 'Papoea Nieuw-Guinese', '26' ]
			],
			[
				[ 'Japanse rijk', '34' ],
				[ 'Italië', '33' ],
				[ 'Republiek Opper Volta', '33' ],
				[ 'Zweden', '31' ],
				[ 'Republiek China', '29' ],
				[ 'Frankrijk', '28' ],
				[ 'Verenigde Staten van Amerika', '28' ],
				[ 'Frans Algerije', '28' ],
				[ 'Arabië', '28' ],
				[ 'Yakutia', '28' ],
				[ 'Papoea Nieuw-Guinese', '27' ],
				[ 'Belgisch Congo', '26' ],
				[ 'Nederlands Oost-Indië', '26' ],
				[ 'Brits Canada', '25' ],
				[ 'Frans Madagascar', '25' ],
				[ 'Venezuela', '24' ]
			],
			[
				[ 'Brits Egypte', '34' ],
				[ 'Ottomaanse Rijk', '34' ],
				[ 'Brits Canada', '33' ],
				[ 'Het Duitse Rijk', '32' ],
				[ 'Communistisch Rusland', '32' ],
				[ 'Arabië', '31' ],
				[ 'Papoea Nieuw-Guinese', '30' ],
				[ 'Frans Algerije', '29' ],
				[ 'Nederlands Oost-Indië', '29' ],
				[ 'Frans Madagascar', '28' ],
				[ 'Frans Marokko', '27' ],
				[ 'Yakutia', '27' ],
				[ 'Belgisch Congo', '26' ],
				[ 'Brits Pakistan', '26' ],
				[ 'Deens Groenland', '25' ],
				[ 'Anglo-Egyptisch Soedan', '25' ]
			],
			[
				[ 'Verenigde Latijns-Amerikaanse Naties', '35' ],
				[ 'Ottomaanse Rijk', '35' ],
				[ 'Brits Birma', '34' ],
				[ 'Communistisch Rusland', '34' ],
				[ 'Nederlands Oost-Indië', '34' ],
				[ 'Papoea Nieuw-Guinese', '31' ],
				[ 'Brits Canada', '30' ],
				[ 'Frans Algerije', '30' ],
				[ 'Frans Marokko', '30' ],
				[ 'Brits Pakistan', '30' ],
				[ 'Canada', '29' ],
				[ 'Chili', '28' ],
				[ 'Nederlands Indonesië', '28' ],
				[ 'Republiek van Argentinië', '26' ],
				[ 'Anglo-Egyptisch Soedan', '26' ],
				[ 'Chinees Sinkiang', '26' ]
			],
			[
				[ 'Communistisch Rusland', '40' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '38' ],
				[ 'Argentinië', '38' ],
				[ 'Brits Egypte', '38' ],
				[ 'Republiek Opper Volta', '37' ],
				[ 'Papoea Nieuw-Guinese', '37' ],
				[ 'Bolivia', '36' ],
				[ 'Frans Algerije', '36' ],
				[ 'Frans Madagascar', '35' ],
				[ 'Anglo-Egyptisch Soedan', '34' ],
				[ 'Ottomaanse Rijk', '33' ],
				[ 'Brits Canada', '32' ],
				[ 'Chili', '32' ],
				[ 'Frans Marokko', '32' ],
				[ 'Brits Pakistan', '32' ],
				[ 'Chinees Sinkiang', '30' ]
			],
			[
				[ 'Italië', '57' ],
				[ 'Arabië', '53' ],
				[ 'Verenigde Staten van Amerika', '48' ],
				[ 'Zweden', '43' ],
				[ 'Het Koninkrijk Engeland', '42' ],
				[ 'Republiek China', '41' ],
				[ 'Argentinië', '40' ],
				[ 'Frans Algerije', '40' ],
				[ 'Republiek Opper Volta', '40' ],
				[ 'Communistisch Rusland', '40' ],
				[ 'Brits Egypte', '39' ],
				[ 'Duits Namibië', '39' ],
				[ 'Papoea Nieuw-Guinese', '39' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '38' ],
				[ 'Frans Madagascar', '38' ],
				[ 'Bolivia', '35' ]
			],
			[
				[ 'Italië', '62' ],
				[ 'Japanse rijk', '61' ],
				[ 'Arabië', '55' ],
				[ 'Verenigde Staten van Amerika', '52' ],
				[ 'Het Koninkrijk Engeland', '45' ],
				[ 'Frans Algerije', '43' ],
				[ 'Republiek Opper Volta', '43' ],
				[ 'Republiek China', '43' ],
				[ 'Zweden', '42' ],
				[ 'Duits Namibië', '41' ],
				[ 'Argentinië', '40' ],
				[ 'Papoea Nieuw-Guinese', '40' ],
				[ 'Brits Egypte', '39' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '38' ],
				[ 'Frans Madagascar', '38' ],
				[ 'Communistisch Rusland', '37' ]
			],
			[
				[ 'Japanse rijk', '63' ],
				[ 'Italië', '60' ],
				[ 'Verenigde Staten van Amerika', '55' ],
				[ 'Het Koninkrijk Engeland', '54' ],
				[ 'Arabië', '54' ],
				[ 'Frans Algerije', '50' ],
				[ 'Zweden', '46' ],
				[ 'Papoea Nieuw-Guinese', '44' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '43' ],
				[ 'Republiek Opper Volta', '43' ],
				[ 'Republiek China', '43' ],
				[ 'Duits Namibië', '41' ],
				[ 'Brits Egypte', '39' ],
				[ 'Communistisch Rusland', '38' ],
				[ 'Frans Madagascar', '37' ],
				[ 'Bolivia', '36' ]
			],
			[
				[ 'Italië', '72' ],
				[ 'Japanse rijk', '64' ],
				[ 'Arabië', '61' ],
				[ 'Het Koninkrijk Engeland', '55' ],
				[ 'Frans Algerije', '52' ],
				[ 'Zweden', '51' ],
				[ 'Bolivia', '49' ],
				[ 'Verenigde Staten van Amerika', '45' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '44' ],
				[ 'Duits Namibië', '43' ],
				[ 'Republiek China', '43' ],
				[ 'Papoea Nieuw-Guinese', '43' ],
				[ 'Republiek Opper Volta', '42' ],
				[ 'Argentinië', '40' ],
				[ 'Brits Egypte', '38' ],
				[ 'Duits Tanzania', '38' ]
			],
			[
				[ 'Italië', '83' ],
				[ 'Zweden', '70' ],
				[ 'Japanse rijk', '70' ],
				[ 'Arabië', '60' ],
				[ 'Het Koninkrijk Engeland', '57' ],
				[ 'Frans Algerije', '55' ],
				[ 'Verenigde Staten van Amerika', '54' ],
				[ 'Republiek China', '48' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '46' ],
				[ 'Duits Namibië', '45' ],
				[ 'Papoea Nieuw-Guinese', '45' ],
				[ 'Republiek Opper Volta', '43' ],
				[ 'Bolivia', '42' ],
				[ 'Argentinië', '40' ],
				[ 'Brits Egypte', '40' ],
				[ 'Duits Tanzania', '40' ]
			],
			[
				[ 'Italië', '92' ],
				[ 'Zweden', '74' ],
				[ 'Japanse rijk', '73' ],
				[ 'Het Koninkrijk Engeland', '58' ],
				[ 'Frans Algerije', '57' ],
				[ 'Arabië', '57' ],
				[ 'Republiek Opper Volta', '55' ],
				[ 'Verenigde Staten van Amerika', '50' ],
				[ 'Republiek China', '50' ],
				[ 'Papoea Nieuw-Guinese', '47' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '46' ],
				[ 'Duits Namibië', '45' ],
				[ 'Brits Egypte', '42' ],
				[ 'Duits Tanzania', '42' ],
				[ 'Argentinië', '41' ],
				[ 'Frans Madagascar', '41' ]
			],
			[
				[ 'Italië', '94' ],
				[ 'Zweden', '78' ],
				[ 'Arabië', '76' ],
				[ 'Japanse rijk', '69' ],
				[ 'Het Koninkrijk Engeland', '63' ],
				[ 'Frans Algerije', '57' ],
				[ 'Papoea Nieuw-Guinese', '55' ],
				[ 'Republiek Opper Volta', '54' ],
				[ 'Republiek China', '53' ],
				[ 'Verenigde Staten van Amerika', '52' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '49' ],
				[ 'Duits Tanzania', '47' ],
				[ 'Frans Madagascar', '43' ],
				[ 'Nederlands Indonesië', '43' ],
				[ 'Argentinië', '39' ],
				[ 'Portugees Mozambique', '39' ]
			],
			[
				[ 'Italië', '104' ],
				[ 'Arabië', '91' ],
				[ 'Zweden', '88' ],
				[ 'Japanse rijk', '85' ],
				[ 'Het Koninkrijk Engeland', '66' ],
				[ 'Frans Algerije', '60' ],
				[ 'Papoea Nieuw-Guinese', '60' ],
				[ 'Verenigde Staten van Amerika', '57' ],
				[ 'Republiek Opper Volta', '57' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '48' ],
				[ 'Duits Tanzania', '45' ],
				[ 'Nederlands Indonesië', '45' ],
				[ 'Frans Madagascar', '44' ],
				[ 'Republiek China', '42' ],
				[ 'Nederlands Oost-Indië', '41' ],
				[ 'Venezuela', '39' ]
			],
			[
				[ 'Italië', '111' ],
				[ 'Japanse rijk', '108' ],
				[ 'Zweden', '98' ],
				[ 'Arabië', '97' ],
				[ 'Het Koninkrijk Engeland', '70' ],
				[ 'Frans Algerije', '69' ],
				[ 'Verenigde Staten van Amerika', '62' ],
				[ 'Papoea Nieuw-Guinese', '60' ],
				[ 'Republiek Opper Volta', '55' ],
				[ 'Argentinië', '53' ],
				[ 'Republiek van Australië', '49' ],
				[ 'Nederlands Indonesië', '48' ],
				[ 'Nederlands Oost-Indië', '47' ],
				[ 'Frans Madagascar', '44' ],
				[ 'Venezuela', '42' ],
				[ 'Brits Canada', '41' ]
			],
			[
				[ 'Italië', '135' ],
				[ 'Japanse rijk', '114' ],
				[ 'Arabië', '105' ],
				[ 'Zweden', '102' ],
				[ 'Frans Algerije', '92' ],
				[ 'Het Koninkrijk Engeland', '64' ],
				[ 'Verenigde Staten van Amerika', '61' ],
				[ 'Papoea Nieuw-Guinese', '59' ],
				[ 'Republiek Opper Volta', '58' ],
				[ 'Nederlands Oost-Indië', '57' ],
				[ 'Argentinië', '54' ],
				[ 'Republiek van Australië', '52' ],
				[ 'Nederlands Indonesië', '49' ],
				[ 'Venezuela', '45' ],
				[ 'Chili', '45' ],
				[ 'Brits Canada', '44' ]
			],
			[
				[ 'Italië', '146' ],
				[ 'Japanse rijk', '125' ],
				[ 'Arabië', '108' ],
				[ 'Zweden', '107' ],
				[ 'Frans Algerije', '97' ],
				[ 'Het Koninkrijk Engeland', '74' ],
				[ 'Verenigde Staten van Amerika', '65' ],
				[ 'Papoea Nieuw-Guinese', '63' ],
				[ 'Nederlands Oost-Indië', '60' ],
				[ 'Argentinië', '59' ],
				[ 'Republiek Opper Volta', '58' ],
				[ 'Republiek van Australië', '55' ],
				[ 'Nederlands Indonesië', '51' ],
				[ 'Brits Canada', '49' ],
				[ 'Chili', '46' ],
				[ 'Duits Tanzania', '45' ]
			],
			[
				[ 'Italië', '148' ],
				[ 'Japanse rijk', '140' ],
				[ 'Arabië', '113' ],
				[ 'Zweden', '112' ],
				[ 'Frans Algerije', '98' ],
				[ 'Het Koninkrijk Engeland', '81' ],
				[ 'Argentinië', '75' ],
				[ 'Verenigde Staten van Amerika', '72' ],
				[ 'Papoea Nieuw-Guinese', '65' ],
				[ 'Nederlands Oost-Indië', '61' ],
				[ 'Republiek Opper Volta', '58' ],
				[ 'Republiek van Australië', '57' ],
				[ 'Brits Canada', '52' ],
				[ 'Chili', '51' ],
				[ 'Duits Tanzania', '46' ],
				[ 'Anglo-Egyptisch Soedan', '42' ]
			],
			[
				[ 'Japanse rijk', '151' ],
				[ 'Italië', '148' ],
				[ 'Arabië', '126' ],
				[ 'Zweden', '117' ],
				[ 'Frans Algerije', '104' ],
				[ 'Het Koninkrijk Engeland', '92' ],
				[ 'Argentinië', '85' ],
				[ 'Verenigde Staten van Amerika', '75' ],
				[ 'Papoea Nieuw-Guinese', '69' ],
				[ 'Brits Canada', '60' ],
				[ 'Republiek Opper Volta', '60' ],
				[ 'Republiek van Australië', '60' ],
				[ 'Chili', '54' ],
				[ 'Duits Tanzania', '48' ],
				[ 'Duits Kameroen', '46' ],
				[ 'Anglo-Egyptisch Soedan', '43' ]
			],
			[
				[ 'Japanse rijk', '176' ],
				[ 'Italië', '149' ],
				[ 'Arabië', '130' ],
				[ 'Zweden', '119' ],
				[ 'Frans Algerije', '112' ],
				[ 'Het Koninkrijk Engeland', '95' ],
				[ 'Argentinië', '82' ],
				[ 'Papoea Nieuw-Guinese', '81' ],
				[ 'Verenigde Staten van Amerika', '67' ],
				[ 'Republiek van Australië', '59' ],
				[ 'Republiek Opper Volta', '58' ],
				[ 'Brits Canada', '57' ],
				[ 'Chili', '57' ],
				[ 'Duits Tanzania', '50' ],
				[ 'Duits Kameroen', '47' ],
				[ 'Anglo-Egyptisch Soedan', '41' ]
			],
			[
				[ 'Japanse rijk', '175' ],
				[ 'Italië', '146' ],
				[ 'Arabië', '122' ],
				[ 'Zweden', '119' ],
				[ 'Frans Algerije', '113' ],
				[ 'Het Koninkrijk Engeland', '95' ],
				[ 'Papoea Nieuw-Guinese', '83' ],
				[ 'Argentinië', '82' ],
				[ 'Verenigde Staten van Amerika', '75' ],
				[ 'Duits Tanzania', '62' ],
				[ 'Republiek van Australië', '62' ],
				[ 'Chili', '61' ],
				[ 'Brits Canada', '57' ],
				[ 'Republiek Opper Volta', '56' ],
				[ 'Duits Kameroen', '41' ],
				[ 'Brits Egypte', '40' ]
			],
			[
				[ 'Japanse rijk', '176' ],
				[ 'Italië', '165' ],
				[ 'Zweden', '125' ],
				[ 'Arabië', '125' ],
				[ 'Frans Algerije', '112' ],
				[ 'Het Koninkrijk Engeland', '98' ],
				[ 'Argentinië', '85' ],
				[ 'Papoea Nieuw-Guinese', '80' ],
				[ 'Duits Tanzania', '70' ],
				[ 'Verenigde Staten van Amerika', '68' ],
				[ 'Chili', '65' ],
				[ 'Republiek van Australië', '65' ],
				[ 'Brits Canada', '53' ],
				[ 'Deens Groenland', '43' ],
				[ 'Brits Egypte', '42' ],
				[ 'Duits Kameroen', '40' ]
			],
			[
				[ 'Japanse rijk', '180' ],
				[ 'Italië', '167' ],
				[ 'Zweden', '126' ],
				[ 'Arabië', '126' ],
				[ 'Frans Algerije', '116' ],
				[ 'Het Koninkrijk Engeland', '99' ],
				[ 'Argentinië', '86' ],
				[ 'Papoea Nieuw-Guinese', '80' ],
				[ 'Duits Tanzania', '74' ],
				[ 'Verenigde Staten van Amerika', '69' ],
				[ 'Chili', '67' ],
				[ 'Republiek van Australië', '67' ],
				[ 'Brits Canada', '49' ],
				[ 'Deens Groenland', '44' ],
				[ 'Duits Kameroen', '43' ],
				[ 'Brits Egypte', '42' ]
			],
			[
				[ 'Japanse rijk', '183' ],
				[ 'Italië', '167' ],
				[ 'Frans Algerije', '132' ],
				[ 'Zweden', '125' ],
				[ 'Arabië', '124' ],
				[ 'Het Koninkrijk Engeland', '99' ],
				[ 'Argentinië', '87' ],
				[ 'Papoea Nieuw-Guinese', '81' ],
				[ 'Duits Tanzania', '77' ],
				[ 'Verenigde Staten van Amerika', '69' ],
				[ 'Republiek van Australië', '68' ],
				[ 'Chili', '67' ],
				[ 'Duits Kameroen', '61' ],
				[ 'Brits Canada', '45' ],
				[ 'Brits Egypte', '42' ],
				[ 'Deens Groenland', '41' ]
			],
			[
				[ 'Japanse rijk', '191' ],
				[ 'Italië', '157' ],
				[ 'Frans Algerije', '147' ],
				[ 'Zweden', '128' ],
				[ 'Arabië', '122' ],
				[ 'Het Koninkrijk Engeland', '102' ],
				[ 'Argentinië', '89' ],
				[ 'Duits Tanzania', '83' ],
				[ 'Papoea Nieuw-Guinese', '83' ],
				[ 'Verenigde Staten van Amerika', '73' ],
				[ 'Republiek van Australië', '70' ],
				[ 'Chili', '64' ],
				[ 'Duits Kameroen', '62' ],
				[ 'Nederlands Oost-Indië', '47' ],
				[ 'Brits Canada', '46' ],
				[ 'Brits Egypte', '43' ]
			],
			[
				[ 'Japanse rijk', '197' ],
				[ 'Italië', '167' ],
				[ 'Frans Algerije', '148' ],
				[ 'Zweden', '127' ],
				[ 'Arabië', '117' ],
				[ 'Het Koninkrijk Engeland', '101' ],
				[ 'Argentinië', '89' ],
				[ 'Duits Tanzania', '88' ],
				[ 'Papoea Nieuw-Guinese', '84' ],
				[ 'Verenigde Staten van Amerika', '74' ],
				[ 'Republiek van Australië', '74' ],
				[ 'Chili', '64' ],
				[ 'Duits Kameroen', '62' ],
				[ 'Nederlands Oost-Indië', '62' ],
				[ 'Brits Canada', '45' ],
				[ 'Brits Egypte', '42' ]
			],
			[
				[ 'Italië', '189' ],
				[ 'Japanse rijk', '179' ],
				[ 'Frans Algerije', '152' ],
				[ 'Zweden', '134' ],
				[ 'Arabië', '118' ],
				[ 'Het Koninkrijk Engeland', '107' ],
				[ 'Duits Tanzania', '96' ],
				[ 'Verenigde Staten van Amerika', '84' ],
				[ 'Papoea Nieuw-Guinese', '82' ],
				[ 'Republiek van Australië', '73' ],
				[ 'Chili', '66' ],
				[ 'Duits Kameroen', '65' ],
				[ 'Argentinië', '51' ],
				[ 'Nederlands Oost-Indië', '49' ],
				[ 'Brits Canada', '48' ],
				[ 'Brits Egypte', '46' ]
			],
			[
				[ 'Italië', '199' ],
				[ 'Japanse rijk', '184' ],
				[ 'Frans Algerije', '171' ],
				[ 'Zweden', '134' ],
				[ 'Het Koninkrijk Engeland', '109' ],
				[ 'Arabië', '105' ],
				[ 'Duits Tanzania', '101' ],
				[ 'Verenigde Staten van Amerika', '88' ],
				[ 'Papoea Nieuw-Guinese', '82' ],
				[ 'Chili', '67' ],
				[ 'Republiek van Australië', '66' ],
				[ 'Duits Kameroen', '65' ],
				[ 'Nederlands Oost-Indië', '51' ],
				[ 'Brits Canada', '49' ],
				[ 'Brits Egypte', '47' ],
				[ 'Canada', '45' ]
			],
			[
				[ 'Italië', '207' ],
				[ 'Japanse rijk', '203' ],
				[ 'Frans Algerije', '186' ],
				[ 'Zweden', '143' ],
				[ 'Duits Tanzania', '133' ],
				[ 'Het Koninkrijk Engeland', '116' ],
				[ 'Verenigde Staten van Amerika', '92' ],
				[ 'Papoea Nieuw-Guinese', '81' ],
				[ 'Chili', '69' ],
				[ 'Republiek van Australië', '69' ],
				[ 'Duits Kameroen', '62' ],
				[ 'Brits Canada', '56' ],
				[ 'Brits Egypte', '54' ],
				[ 'Canada', '49' ],
				[ 'Argentinië', '43' ],
				[ 'Anglo-Egyptisch Soedan', '43' ]
			],
			[
				[ 'Japanse rijk', '257' ],
				[ 'Italië', '227' ],
				[ 'Frans Algerije', '188' ],
				[ 'Zweden', '143' ],
				[ 'Duits Tanzania', '143' ],
				[ 'Het Koninkrijk Engeland', '115' ],
				[ 'Verenigde Staten van Amerika', '94' ],
				[ 'Duits Kameroen', '77' ],
				[ 'Chili', '69' ],
				[ 'Papoea Nieuw-Guinese', '63' ],
				[ 'Brits Canada', '59' ],
				[ 'Brits Egypte', '54' ],
				[ 'Republiek van Australië', '53' ],
				[ 'Canada', '51' ],
				[ 'Argentinië', '49' ],
				[ 'Anglo-Egyptisch Soedan', '42' ]
			],
			[
				[ 'Japanse rijk', '306' ],
				[ 'Italië', '221' ],
				[ 'Frans Algerije', '194' ],
				[ 'Duits Tanzania', '161' ],
				[ 'Zweden', '152' ],
				[ 'Het Koninkrijk Engeland', '119' ],
				[ 'Verenigde Staten van Amerika', '98' ],
				[ 'Duits Kameroen', '72' ],
				[ 'Chili', '70' ],
				[ 'Brits Canada', '64' ],
				[ 'Canada', '55' ],
				[ 'Argentinië', '55' ],
				[ 'Anglo-Egyptisch Soedan', '44' ],
				[ 'Republiek van Australië', '39' ],
				[ 'Frans Madagascar', '35' ],
				[ 'Brits Egypte', '33' ]
			]
		]
}

module.exports = responseExample;
