var responseExampleLong = {
	dayIndexExample:
		[
			[
				[ 'Spanje', '20' ],
				[ 'Frankrijk', '20' ],
				[ 'Het Duitse Rijk', '20' ],
				[ 'Het Koninkrijk Engeland', '20' ],
				[ 'Oostenrijk-Hongarije', '20' ],
				[ 'Italië', '20' ],
				[ 'Griekenland', '20' ],
				[ 'Noorwegen', '20' ],
				[ 'Zweden', '20' ],
				[ 'Finland', '20' ],
				[ 'Schotland', '20' ],
				[ 'Ierland', '20' ],
				[ 'Wit-Russische Republiek', '20' ],
				[ 'Canada', '20' ],
				[ 'Brits Canada', '20' ],
				[ 'Baffin', '20' ],
				[ 'Deens Groenland', '20' ],
				[ 'Federale Staten van Amerika', '20' ],
				[ 'Verenigde Staten van Amerika', '20' ],
				[ 'Confederale Staten van Amerika', '20' ],
				[ 'Mexico', '20' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '20' ],
				[ 'Caribische Eilandenrepubliek', '20' ],
				[ 'Venezuela', '20' ],
				[ 'Colombia', '20' ],
				[ 'Verenigde Staten van Brazilië', '20' ],
				[ 'Peru', '20' ],
				[ 'Argentinië', '20' ],
				[ 'Republiek van Argentinië', '20' ],
				[ 'Chili', '20' ],
				[ 'Republiek van Piratini', '20' ],
				[ 'Ecuador', '20' ],
				[ 'Bolivia', '20' ],
				[ 'Frans Algerije', '20' ],
				[ 'Brits Egypte', '20' ],
				[ 'Frans West-Afrika', '20' ],
				[ 'Abessinië', '20' ],
				[ 'Anglo-Egyptisch Soedan', '20' ],
				[ 'Unie van Zuid-Afrika', '20' ],
				[ 'Belgisch Congo', '20' ],
				[ 'Duits Kameroen', '20' ],
				[ 'Duits Namibië', '20' ],
				[ 'Duits Tanzania', '20' ],
				[ 'Portugees Mozambique', '20' ],
				[ 'Frans Madagascar', '20' ],
				[ 'Republiek Opper Volta', '20' ],
				[ 'Frans Marokko', '20' ],
				[ 'Unie van Indochina', '20' ],
				[ 'Perzië', '20' ],
				[ 'Ottomaanse Rijk', '20' ],
				[ 'Japanse rijk', '20' ],
				[ 'Brits Pakistan', '20' ],
				[ 'Brits Birma', '20' ],
				[ 'Brits-India', '20' ],
				[ 'Arabië', '20' ],
				[ 'Chinees Sinkiang', '20' ],
				[ 'Communistisch Rusland', '20' ],
				[ 'Russische Rijk', '20' ],
				[ 'Siberië', '20' ],
				[ 'Yakutia', '20' ],
				[ 'Archangelsk', '20' ],
				[ 'Kazachstan', '20' ],
				[ 'Mantsjoerije', '20' ],
				[ 'Chinese Rijk', '20' ],
				[ 'Republiek China', '20' ],
				[ 'Koreaanse Rijk', '20' ],
				[ 'Siam', '20' ],
				[ 'Australië', '20' ],
				[ 'Republiek van Australië', '20' ],
				[ 'Brits Australië', '20' ],
				[ 'Nederlands Oost-Indië', '20' ],
				[ 'Nederlands Indonesië', '20' ],
				[ 'Amerikaanse Filipijnen', '20' ],
				[ 'Republiek van Filipijns Moro', '20' ],
				[ 'Brits Nieuw-Zeeland', '20' ],
				[ 'Nederlands Nieuw-Guinea', '20' ],
				[ 'Papoea Nieuw-Guinese', '20' ],
				[ 'Republiek Amazonas', '10' ],
				[ 'Brits Kashmir', '5' ],
				[ 'Nepal', '5' ]
			],
			[
				[ 'Kazachstan', '25' ],
				[ 'Argentinië', '24' ],
				[ 'Spanje', '21' ],
				[ 'Het Koninkrijk Engeland', '21' ],
				[ 'Italië', '21' ],
				[ 'Zweden', '21' ],
				[ 'Canada', '21' ],
				[ 'Confederale Staten van Amerika', '21' ],
				[ 'Belgisch Congo', '21' ],
				[ 'Duits Namibië', '21' ],
				[ 'Japanse rijk', '21' ],
				[ 'Arabië', '21' ],
				[ 'Republiek China', '21' ],
				[ 'Australië', '21' ],
				[ 'Republiek van Australië', '21' ],
				[ 'Nederlands Oost-Indië', '21' ],
				[ 'Het Duitse Rijk', '20' ],
				[ 'Griekenland', '20' ],
				[ 'Brits Canada', '20' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '20' ],
				[ 'Caribische Eilandenrepubliek', '20' ],
				[ 'Frans Algerije', '20' ],
				[ 'Unie van Zuid-Afrika', '20' ],
				[ 'Duits Kameroen', '20' ],
				[ 'Portugees Mozambique', '20' ],
				[ 'Frans Madagascar', '20' ],
				[ 'Republiek Opper Volta', '20' ],
				[ 'Yakutia', '20' ],
				[ 'Frankrijk', '19' ],
				[ 'Oostenrijk-Hongarije', '19' ],
				[ 'Noorwegen', '19' ],
				[ 'Finland', '19' ],
				[ 'Schotland', '19' ],
				[ 'Ierland', '19' ],
				[ 'Wit-Russische Republiek', '19' ],
				[ 'Baffin', '19' ],
				[ 'Deens Groenland', '19' ],
				[ 'Federale Staten van Amerika', '19' ],
				[ 'Verenigde Staten van Amerika', '19' ],
				[ 'Mexico', '19' ],
				[ 'Venezuela', '19' ],
				[ 'Colombia', '19' ],
				[ 'Verenigde Staten van Brazilië', '19' ],
				[ 'Peru', '19' ],
				[ 'Republiek van Argentinië', '19' ],
				[ 'Chili', '19' ],
				[ 'Republiek van Piratini', '19' ],
				[ 'Ecuador', '19' ],
				[ 'Bolivia', '19' ],
				[ 'Brits Egypte', '19' ],
				[ 'Frans West-Afrika', '19' ],
				[ 'Abessinië', '19' ],
				[ 'Anglo-Egyptisch Soedan', '19' ],
				[ 'Duits Tanzania', '19' ],
				[ 'Frans Marokko', '19' ],
				[ 'Unie van Indochina', '19' ],
				[ 'Perzië', '19' ],
				[ 'Ottomaanse Rijk', '19' ],
				[ 'Brits Pakistan', '19' ],
				[ 'Brits Birma', '19' ],
				[ 'Brits-India', '19' ],
				[ 'Chinees Sinkiang', '19' ],
				[ 'Communistisch Rusland', '19' ],
				[ 'Russische Rijk', '19' ],
				[ 'Siberië', '19' ],
				[ 'Archangelsk', '19' ],
				[ 'Mantsjoerije', '19' ],
				[ 'Chinese Rijk', '19' ],
				[ 'Koreaanse Rijk', '19' ],
				[ 'Siam', '19' ],
				[ 'Brits Australië', '19' ],
				[ 'Nederlands Indonesië', '19' ],
				[ 'Amerikaanse Filipijnen', '19' ],
				[ 'Republiek van Filipijns Moro', '19' ],
				[ 'Brits Nieuw-Zeeland', '19' ],
				[ 'Nederlands Nieuw-Guinea', '19' ],
				[ 'Papoea Nieuw-Guinese', '19' ],
				[ 'Republiek Amazonas', '10' ],
				[ 'Brits Kashmir', '5' ],
				[ 'Nepal', '5' ]
			],
			[
				[ 'Argentinië', '32' ],
				[ 'Japanse rijk', '31' ],
				[ 'Belgisch Congo', '26' ],
				[ 'Republiek Opper Volta', '26' ],
				[ 'Het Koninkrijk Engeland', '25' ],
				[ 'Arabië', '25' ],
				[ 'Kazachstan', '24' ],
				[ 'Frans Algerije', '23' ],
				[ 'Frankrijk', '21' ],
				[ 'Het Duitse Rijk', '21' ],
				[ 'Italië', '21' ],
				[ 'Verenigde Staten van Amerika', '21' ],
				[ 'Abessinië', '21' ],
				[ 'Duits Namibië', '21' ],
				[ 'Koreaanse Rijk', '21' ],
				[ 'Australië', '21' ],
				[ 'Nederlands Indonesië', '21' ],
				[ 'Griekenland', '20' ],
				[ 'Noorwegen', '20' ],
				[ 'Zweden', '20' ],
				[ 'Finland', '20' ],
				[ 'Ierland', '20' ],
				[ 'Canada', '20' ],
				[ 'Brits Canada', '20' ],
				[ 'Baffin', '20' ],
				[ 'Federale Staten van Amerika', '20' ],
				[ 'Mexico', '20' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '20' ],
				[ 'Caribische Eilandenrepubliek', '20' ],
				[ 'Colombia', '20' ],
				[ 'Peru', '20' ],
				[ 'Republiek van Argentinië', '20' ],
				[ 'Bolivia', '20' ],
				[ 'Brits Egypte', '20' ],
				[ 'Frans West-Afrika', '20' ],
				[ 'Anglo-Egyptisch Soedan', '20' ],
				[ 'Unie van Zuid-Afrika', '20' ],
				[ 'Duits Kameroen', '20' ],
				[ 'Duits Tanzania', '20' ],
				[ 'Portugees Mozambique', '20' ],
				[ 'Frans Madagascar', '20' ],
				[ 'Frans Marokko', '20' ],
				[ 'Brits Birma', '20' ],
				[ 'Chinees Sinkiang', '20' ],
				[ 'Communistisch Rusland', '20' ],
				[ 'Russische Rijk', '20' ],
				[ 'Yakutia', '20' ],
				[ 'Archangelsk', '20' ],
				[ 'Mantsjoerije', '20' ],
				[ 'Chinese Rijk', '20' ],
				[ 'Republiek van Australië', '20' ],
				[ 'Nederlands Oost-Indië', '20' ],
				[ 'Amerikaanse Filipijnen', '20' ],
				[ 'Nederlands Nieuw-Guinea', '20' ],
				[ 'Papoea Nieuw-Guinese', '20' ],
				[ 'Oostenrijk-Hongarije', '19' ],
				[ 'Wit-Russische Republiek', '19' ],
				[ 'Deens Groenland', '19' ],
				[ 'Venezuela', '19' ],
				[ 'Verenigde Staten van Brazilië', '19' ],
				[ 'Chili', '19' ],
				[ 'Republiek van Piratini', '19' ],
				[ 'Ecuador', '19' ],
				[ 'Unie van Indochina', '19' ],
				[ 'Perzië', '19' ],
				[ 'Ottomaanse Rijk', '19' ],
				[ 'Brits Pakistan', '19' ],
				[ 'Brits-India', '19' ],
				[ 'Siberië', '19' ],
				[ 'Republiek China', '19' ],
				[ 'Siam', '19' ],
				[ 'Republiek van Filipijns Moro', '19' ],
				[ 'Confederale Staten van Amerika', '18' ],
				[ 'Brits Nieuw-Zeeland', '17' ],
				[ 'Spanje', '16' ],
				[ 'Brits Australië', '16' ],
				[ 'Republiek Amazonas', '10' ],
				[ 'Schotland', '6' ],
				[ 'Brits Kashmir', '5' ],
				[ 'Nepal', '5' ]
			],
			[
				[ 'Japanse rijk', '37' ],
				[ 'Argentinië', '34' ],
				[ 'Venezuela', '31' ],
				[ 'Republiek Opper Volta', '28' ],
				[ 'Het Duitse Rijk', '27' ],
				[ 'Het Koninkrijk Engeland', '27' ],
				[ 'Italië', '27' ],
				[ 'Zweden', '26' ],
				[ 'Belgisch Congo', '26' ],
				[ 'Duits Namibië', '26' ],
				[ 'Frankrijk', '25' ],
				[ 'Frans Algerije', '25' ],
				[ 'Unie van Zuid-Afrika', '25' ],
				[ 'Nederlands Oost-Indië', '25' ],
				[ 'Arabië', '24' ],
				[ 'Republiek China', '23' ],
				[ 'Baffin', '21' ],
				[ 'Republiek van Argentinië', '21' ],
				[ 'Ecuador', '21' ],
				[ 'Brits Egypte', '21' ],
				[ 'Abessinië', '21' ],
				[ 'Anglo-Egyptisch Soedan', '21' ],
				[ 'Duits Tanzania', '21' ],
				[ 'Frans Madagascar', '21' ],
				[ 'Frans Marokko', '21' ],
				[ 'Ottomaanse Rijk', '21' ],
				[ 'Brits Pakistan', '21' ],
				[ 'Brits Birma', '21' ],
				[ 'Brits-India', '21' ],
				[ 'Chinees Sinkiang', '21' ],
				[ 'Communistisch Rusland', '21' ],
				[ 'Archangelsk', '21' ],
				[ 'Chinese Rijk', '21' ],
				[ 'Koreaanse Rijk', '21' ],
				[ 'Siam', '21' ],
				[ 'Australië', '21' ],
				[ 'Republiek van Australië', '21' ],
				[ 'Nederlands Indonesië', '21' ],
				[ 'Papoea Nieuw-Guinese', '21' ],
				[ 'Oostenrijk-Hongarije', '20' ],
				[ 'Griekenland', '20' ],
				[ 'Finland', '20' ],
				[ 'Ierland', '20' ],
				[ 'Wit-Russische Republiek', '20' ],
				[ 'Brits Canada', '20' ],
				[ 'Deens Groenland', '20' ],
				[ 'Verenigde Staten van Amerika', '20' ],
				[ 'Mexico', '20' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '20' ],
				[ 'Caribische Eilandenrepubliek', '20' ],
				[ 'Colombia', '20' ],
				[ 'Verenigde Staten van Brazilië', '20' ],
				[ 'Peru', '20' ],
				[ 'Chili', '20' ],
				[ 'Republiek van Piratini', '20' ],
				[ 'Bolivia', '20' ],
				[ 'Frans West-Afrika', '20' ],
				[ 'Unie van Indochina', '20' ],
				[ 'Perzië', '20' ],
				[ 'Russische Rijk', '20' ],
				[ 'Yakutia', '20' ],
				[ 'Kazachstan', '20' ],
				[ 'Mantsjoerije', '20' ],
				[ 'Amerikaanse Filipijnen', '20' ],
				[ 'Republiek van Filipijns Moro', '20' ],
				[ 'Canada', '19' ],
				[ 'Federale Staten van Amerika', '19' ],
				[ 'Confederale Staten van Amerika', '19' ],
				[ 'Portugees Mozambique', '19' ],
				[ 'Siberië', '19' ],
				[ 'Brits Nieuw-Zeeland', '18' ],
				[ 'Duits Kameroen', '17' ],
				[ 'Brits Australië', '17' ],
				[ 'Nederlands Nieuw-Guinea', '16' ],
				[ 'Spanje', '12' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Noorwegen', '8' ],
				[ 'Brits Kashmir', '5' ],
				[ 'Nepal', '5' ],
				[ 'Schotland', '3' ]
			],
			[
				[ 'Argentinië', '37' ],
				[ 'Italië', '32' ],
				[ 'Duits Namibië', '32' ],
				[ 'Brits Birma', '32' ],
				[ 'Frankrijk', '31' ],
				[ 'Republiek Opper Volta', '31' ],
				[ 'Het Duitse Rijk', '29' ],
				[ 'Het Koninkrijk Engeland', '29' ],
				[ 'Japanse rijk', '29' ],
				[ 'Frans Algerije', '28' ],
				[ 'Zweden', '27' ],
				[ 'Belgisch Congo', '27' ],
				[ 'Republiek China', '27' ],
				[ 'Verenigde Staten van Amerika', '26' ],
				[ 'Venezuela', '26' ],
				[ 'Arabië', '26' ],
				[ 'Nederlands Oost-Indië', '26' ],
				[ 'Papoea Nieuw-Guinese', '26' ],
				[ 'Frans Madagascar', '25' ],
				[ 'Canada', '23' ],
				[ 'Brits Canada', '23' ],
				[ 'Unie van Zuid-Afrika', '23' ],
				[ 'Finland', '22' ],
				[ 'Brits Egypte', '22' ],
				[ 'Anglo-Egyptisch Soedan', '22' ],
				[ 'Frans Marokko', '22' ],
				[ 'Ottomaanse Rijk', '22' ],
				[ 'Brits Pakistan', '22' ],
				[ 'Communistisch Rusland', '22' ],
				[ 'Australië', '22' ],
				[ 'Ierland', '21' ],
				[ 'Wit-Russische Republiek', '21' ],
				[ 'Deens Groenland', '21' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '21' ],
				[ 'Caribische Eilandenrepubliek', '21' ],
				[ 'Colombia', '21' ],
				[ 'Republiek van Argentinië', '21' ],
				[ 'Chili', '21' ],
				[ 'Ecuador', '21' ],
				[ 'Frans West-Afrika', '21' ],
				[ 'Duits Tanzania', '21' ],
				[ 'Unie van Indochina', '21' ],
				[ 'Perzië', '21' ],
				[ 'Chinees Sinkiang', '21' ],
				[ 'Yakutia', '21' ],
				[ 'Mantsjoerije', '21' ],
				[ 'Chinese Rijk', '21' ],
				[ 'Koreaanse Rijk', '21' ],
				[ 'Siam', '21' ],
				[ 'Republiek van Filipijns Moro', '21' ],
				[ 'Baffin', '20' ],
				[ 'Mexico', '20' ],
				[ 'Verenigde Staten van Brazilië', '20' ],
				[ 'Republiek van Piratini', '20' ],
				[ 'Bolivia', '20' ],
				[ 'Abessinië', '20' ],
				[ 'Duits Kameroen', '20' ],
				[ 'Portugees Mozambique', '20' ],
				[ 'Siberië', '20' ],
				[ 'Archangelsk', '20' ],
				[ 'Republiek van Australië', '20' ],
				[ 'Nederlands Indonesië', '20' ],
				[ 'Amerikaanse Filipijnen', '20' ],
				[ 'Oostenrijk-Hongarije', '19' ],
				[ 'Griekenland', '19' ],
				[ 'Peru', '19' ],
				[ 'Brits-India', '19' ],
				[ 'Russische Rijk', '19' ],
				[ 'Kazachstan', '19' ],
				[ 'Brits Australië', '17' ],
				[ 'Brits Nieuw-Zeeland', '17' ],
				[ 'Confederale Staten van Amerika', '16' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Federale Staten van Amerika', '8' ],
				[ 'Nederlands Nieuw-Guinea', '6' ],
				[ 'Spanje', '5' ],
				[ 'Brits Kashmir', '5' ],
				[ 'Nepal', '5' ],
				[ 'Schotland', '2' ],
				[ 'Noorwegen', '1' ]
			],
			[
				[ 'Argentinië', '40' ],
				[ 'Het Duitse Rijk', '39' ],
				[ 'Duits Namibië', '39' ],
				[ 'Het Koninkrijk Engeland', '37' ],
				[ 'Brits Birma', '36' ],
				[ 'Brits Egypte', '34' ],
				[ 'Japanse rijk', '34' ],
				[ 'Italië', '33' ],
				[ 'Republiek Opper Volta', '33' ],
				[ 'Zweden', '31' ],
				[ 'Republiek China', '29' ],
				[ 'Frankrijk', '28' ],
				[ 'Verenigde Staten van Amerika', '28' ],
				[ 'Frans Algerije', '28' ],
				[ 'Arabië', '28' ],
				[ 'Yakutia', '28' ],
				[ 'Papoea Nieuw-Guinese', '27' ],
				[ 'Belgisch Congo', '26' ],
				[ 'Nederlands Oost-Indië', '26' ],
				[ 'Brits Canada', '25' ],
				[ 'Frans Madagascar', '25' ],
				[ 'Venezuela', '24' ],
				[ 'Chili', '24' ],
				[ 'Anglo-Egyptisch Soedan', '24' ],
				[ 'Frans Marokko', '24' ],
				[ 'Brits Pakistan', '24' ],
				[ 'Communistisch Rusland', '24' ],
				[ 'Ierland', '23' ],
				[ 'Deens Groenland', '23' ],
				[ 'Caribische Eilandenrepubliek', '23' ],
				[ 'Ecuador', '23' ],
				[ 'Unie van Indochina', '23' ],
				[ 'Perzië', '23' ],
				[ 'Ottomaanse Rijk', '23' ],
				[ 'Chinees Sinkiang', '23' ],
				[ 'Siam', '23' ],
				[ 'Republiek van Filipijns Moro', '23' ],
				[ 'Finland', '22' ],
				[ 'Canada', '22' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '22' ],
				[ 'Colombia', '22' ],
				[ 'Siberië', '22' ],
				[ 'Mantsjoerije', '22' ],
				[ 'Amerikaanse Filipijnen', '22' ],
				[ 'Wit-Russische Republiek', '21' ],
				[ 'Bolivia', '21' ],
				[ 'Duits Kameroen', '21' ],
				[ 'Portugees Mozambique', '21' ],
				[ 'Republiek van Australië', '21' ],
				[ 'Republiek van Argentinië', '20' ],
				[ 'Republiek van Piratini', '20' ],
				[ 'Duits Tanzania', '20' ],
				[ 'Russische Rijk', '20' ],
				[ 'Archangelsk', '20' ],
				[ 'Brits Nieuw-Zeeland', '20' ],
				[ 'Griekenland', '19' ],
				[ 'Verenigde Staten van Brazilië', '19' ],
				[ 'Peru', '19' ],
				[ 'Frans West-Afrika', '19' ],
				[ 'Abessinië', '19' ],
				[ 'Chinese Rijk', '19' ],
				[ 'Nederlands Indonesië', '19' ],
				[ 'Baffin', '18' ],
				[ 'Brits-India', '17' ],
				[ 'Kazachstan', '17' ],
				[ 'Brits Australië', '17' ],
				[ 'Oostenrijk-Hongarije', '16' ],
				[ 'Mexico', '15' ],
				[ 'Confederale Staten van Amerika', '12' ],
				[ 'Koreaanse Rijk', '10' ],
				[ 'Australië', '9' ],
				[ 'Republiek Amazonas', '9' ],
				[ 'Unie van Zuid-Afrika', '5' ],
				[ 'Nederlands Nieuw-Guinea', '5' ],
				[ 'Nepal', '5' ],
				[ 'Brits Kashmir', '4' ],
				[ 'Schotland', '3' ],
				[ 'Federale Staten van Amerika', '3' ],
				[ 'Spanje', '2' ],
				[ 'Noorwegen', '0' ]
			],
			[
				[ 'Japanse rijk', '49' ],
				[ 'Duits Namibië', '43' ],
				[ 'Het Koninkrijk Engeland', '42' ],
				[ 'Republiek China', '41' ],
				[ 'Argentinië', '39' ],
				[ 'Verenigde Staten van Amerika', '38' ],
				[ 'Brits Birma', '36' ],
				[ 'Republiek Opper Volta', '35' ],
				[ 'Italië', '34' ],
				[ 'Zweden', '34' ],
				[ 'Brits Egypte', '34' ],
				[ 'Ottomaanse Rijk', '34' ],
				[ 'Brits Canada', '33' ],
				[ 'Het Duitse Rijk', '32' ],
				[ 'Communistisch Rusland', '32' ],
				[ 'Arabië', '31' ],
				[ 'Papoea Nieuw-Guinese', '30' ],
				[ 'Frans Algerije', '29' ],
				[ 'Nederlands Oost-Indië', '29' ],
				[ 'Frans Madagascar', '28' ],
				[ 'Frans Marokko', '27' ],
				[ 'Yakutia', '27' ],
				[ 'Belgisch Congo', '26' ],
				[ 'Brits Pakistan', '26' ],
				[ 'Deens Groenland', '25' ],
				[ 'Anglo-Egyptisch Soedan', '25' ],
				[ 'Chili', '24' ],
				[ 'Mantsjoerije', '24' ],
				[ 'Ierland', '23' ],
				[ 'Canada', '23' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '23' ],
				[ 'Venezuela', '23' ],
				[ 'Ecuador', '23' ],
				[ 'Bolivia', '23' ],
				[ 'Duits Kameroen', '23' ],
				[ 'Chinees Sinkiang', '23' ],
				[ 'Russische Rijk', '23' ],
				[ 'Siam', '23' ],
				[ 'Republiek van Australië', '23' ],
				[ 'Amerikaanse Filipijnen', '23' ],
				[ 'Republiek van Filipijns Moro', '23' ],
				[ 'Colombia', '22' ],
				[ 'Republiek van Argentinië', '22' ],
				[ 'Duits Tanzania', '22' ],
				[ 'Portugees Mozambique', '22' ],
				[ 'Unie van Indochina', '22' ],
				[ 'Perzië', '22' ],
				[ 'Griekenland', '21' ],
				[ 'Wit-Russische Republiek', '21' ],
				[ 'Baffin', '21' ],
				[ 'Peru', '21' ],
				[ 'Republiek van Piratini', '21' ],
				[ 'Siberië', '21' ],
				[ 'Nederlands Indonesië', '21' ],
				[ 'Brits Nieuw-Zeeland', '21' ],
				[ 'Abessinië', '19' ],
				[ 'Verenigde Staten van Brazilië', '18' ],
				[ 'Archangelsk', '18' ],
				[ 'Chinese Rijk', '17' ],
				[ 'Brits Australië', '17' ],
				[ 'Brits-India', '16' ],
				[ 'Kazachstan', '15' ],
				[ 'Oostenrijk-Hongarije', '13' ],
				[ 'Frans West-Afrika', '13' ],
				[ 'Frankrijk', '12' ],
				[ 'Confederale Staten van Amerika', '11' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Finland', '10' ],
				[ 'Caribische Eilandenrepubliek', '10' ],
				[ 'Mexico', '9' ],
				[ 'Australië', '6' ],
				[ 'Nepal', '5' ],
				[ 'Brits Kashmir', '4' ],
				[ 'Nederlands Nieuw-Guinea', '3' ],
				[ 'Schotland', '2' ],
				[ 'Spanje', '1' ],
				[ 'Noorwegen', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Koreaanse Rijk', '0' ]
			],
			[
				[ 'Japanse rijk', '53' ],
				[ 'Verenigde Staten van Amerika', '48' ],
				[ 'Duits Namibië', '45' ],
				[ 'Zweden', '44' ],
				[ 'Arabië', '44' ],
				[ 'Het Koninkrijk Engeland', '43' ],
				[ 'Republiek China', '43' ],
				[ 'Italië', '41' ],
				[ 'Argentinië', '39' ],
				[ 'Brits Egypte', '37' ],
				[ 'Frans Madagascar', '36' ],
				[ 'Republiek Opper Volta', '36' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '35' ],
				[ 'Ottomaanse Rijk', '35' ],
				[ 'Brits Birma', '34' ],
				[ 'Communistisch Rusland', '34' ],
				[ 'Nederlands Oost-Indië', '34' ],
				[ 'Papoea Nieuw-Guinese', '31' ],
				[ 'Brits Canada', '30' ],
				[ 'Frans Algerije', '30' ],
				[ 'Frans Marokko', '30' ],
				[ 'Brits Pakistan', '30' ],
				[ 'Canada', '29' ],
				[ 'Chili', '28' ],
				[ 'Nederlands Indonesië', '28' ],
				[ 'Republiek van Argentinië', '26' ],
				[ 'Anglo-Egyptisch Soedan', '26' ],
				[ 'Chinees Sinkiang', '26' ],
				[ 'Republiek van Australië', '26' ],
				[ 'Deens Groenland', '25' ],
				[ 'Bolivia', '24' ],
				[ 'Duits Tanzania', '24' ],
				[ 'Portugees Mozambique', '24' ],
				[ 'Russische Rijk', '24' ],
				[ 'Mantsjoerije', '24' ],
				[ 'Amerikaanse Filipijnen', '24' ],
				[ 'Ecuador', '23' ],
				[ 'Unie van Indochina', '23' ],
				[ 'Siam', '23' ],
				[ 'Het Duitse Rijk', '22' ],
				[ 'Venezuela', '22' ],
				[ 'Colombia', '22' ],
				[ 'Duits Kameroen', '22' ],
				[ 'Perzië', '22' ],
				[ 'Griekenland', '21' ],
				[ 'Ierland', '21' ],
				[ 'Peru', '21' ],
				[ 'Siberië', '21' ],
				[ 'Republiek van Filipijns Moro', '21' ],
				[ 'Wit-Russische Republiek', '20' ],
				[ 'Baffin', '20' ],
				[ 'Republiek van Piratini', '20' ],
				[ 'Abessinië', '20' ],
				[ 'Yakutia', '20' ],
				[ 'Brits Nieuw-Zeeland', '19' ],
				[ 'Verenigde Staten van Brazilië', '17' ],
				[ 'Chinese Rijk', '16' ],
				[ 'Brits-India', '15' ],
				[ 'Brits Australië', '15' ],
				[ 'Kazachstan', '13' ],
				[ 'Confederale Staten van Amerika', '12' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Frankrijk', '10' ],
				[ 'Caribische Eilandenrepubliek', '10' ],
				[ 'Oostenrijk-Hongarije', '9' ],
				[ 'Belgisch Congo', '7' ],
				[ 'Archangelsk', '7' ],
				[ 'Australië', '7' ],
				[ 'Nepal', '6' ],
				[ 'Frans West-Afrika', '5' ],
				[ 'Nederlands Nieuw-Guinea', '3' ],
				[ 'Brits Kashmir', '3' ],
				[ 'Finland', '2' ],
				[ 'Schotland', '2' ],
				[ 'Spanje', '1' ],
				[ 'Noorwegen', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Koreaanse Rijk', '0' ]
			],
			[
				[ 'Japanse rijk', '56' ],
				[ 'Italië', '51' ],
				[ 'Verenigde Staten van Amerika', '48' ],
				[ 'Duits Namibië', '47' ],
				[ 'Arabië', '45' ],
				[ 'Republiek China', '44' ],
				[ 'Zweden', '42' ],
				[ 'Het Koninkrijk Engeland', '41' ],
				[ 'Communistisch Rusland', '40' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '38' ],
				[ 'Argentinië', '38' ],
				[ 'Brits Egypte', '38' ],
				[ 'Republiek Opper Volta', '37' ],
				[ 'Papoea Nieuw-Guinese', '37' ],
				[ 'Bolivia', '36' ],
				[ 'Frans Algerije', '36' ],
				[ 'Frans Madagascar', '35' ],
				[ 'Anglo-Egyptisch Soedan', '34' ],
				[ 'Ottomaanse Rijk', '33' ],
				[ 'Brits Canada', '32' ],
				[ 'Chili', '32' ],
				[ 'Frans Marokko', '32' ],
				[ 'Brits Pakistan', '32' ],
				[ 'Chinees Sinkiang', '30' ],
				[ 'Nederlands Oost-Indië', '30' ],
				[ 'Republiek van Australië', '29' ],
				[ 'Canada', '28' ],
				[ 'Brits Birma', '28' ],
				[ 'Republiek van Argentinië', '27' ],
				[ 'Amerikaanse Filipijnen', '27' ],
				[ 'Nederlands Indonesië', '26' ],
				[ 'Ecuador', '24' ],
				[ 'Duits Tanzania', '24' ],
				[ 'Portugees Mozambique', '24' ],
				[ 'Russische Rijk', '24' ],
				[ 'Mantsjoerije', '24' ],
				[ 'Colombia', '23' ],
				[ 'Unie van Indochina', '23' ],
				[ 'Siam', '23' ],
				[ 'Griekenland', '22' ],
				[ 'Peru', '22' ],
				[ 'Duits Kameroen', '22' ],
				[ 'Wit-Russische Republiek', '21' ],
				[ 'Deens Groenland', '21' ],
				[ 'Abessinië', '21' ],
				[ 'Siberië', '21' ],
				[ 'Ierland', '20' ],
				[ 'Perzië', '20' ],
				[ 'Venezuela', '19' ],
				[ 'Republiek van Piratini', '19' ],
				[ 'Verenigde Staten van Brazilië', '18' ],
				[ 'Republiek van Filipijns Moro', '18' ],
				[ 'Brits Nieuw-Zeeland', '18' ],
				[ 'Het Duitse Rijk', '17' ],
				[ 'Chinese Rijk', '16' ],
				[ 'Baffin', '15' ],
				[ 'Brits-India', '14' ],
				[ 'Brits Australië', '13' ],
				[ 'Frankrijk', '12' ],
				[ 'Yakutia', '12' ],
				[ 'Kazachstan', '12' ],
				[ 'Caribische Eilandenrepubliek', '11' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Confederale Staten van Amerika', '10' ],
				[ 'Australië', '7' ],
				[ 'Nepal', '6' ],
				[ 'Frans West-Afrika', '4' ],
				[ 'Archangelsk', '4' ],
				[ 'Nederlands Nieuw-Guinea', '3' ],
				[ 'Brits Kashmir', '3' ],
				[ 'Schotland', '2' ],
				[ 'Spanje', '1' ],
				[ 'Oostenrijk-Hongarije', '1' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Koreaanse Rijk', '0' ]
			],
			[
				[ 'Japanse rijk', '59' ],
				[ 'Italië', '57' ],
				[ 'Arabië', '53' ],
				[ 'Verenigde Staten van Amerika', '48' ],
				[ 'Zweden', '43' ],
				[ 'Het Koninkrijk Engeland', '42' ],
				[ 'Republiek China', '41' ],
				[ 'Argentinië', '40' ],
				[ 'Frans Algerije', '40' ],
				[ 'Republiek Opper Volta', '40' ],
				[ 'Communistisch Rusland', '40' ],
				[ 'Brits Egypte', '39' ],
				[ 'Duits Namibië', '39' ],
				[ 'Papoea Nieuw-Guinese', '39' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '38' ],
				[ 'Frans Madagascar', '38' ],
				[ 'Bolivia', '35' ],
				[ 'Frans Marokko', '34' ],
				[ 'Brits Canada', '33' ],
				[ 'Chili', '33' ],
				[ 'Anglo-Egyptisch Soedan', '33' ],
				[ 'Brits Pakistan', '33' ],
				[ 'Republiek van Australië', '33' ],
				[ 'Nederlands Oost-Indië', '32' ],
				[ 'Brits Birma', '31' ],
				[ 'Chinees Sinkiang', '30' ],
				[ 'Canada', '28' ],
				[ 'Nederlands Indonesië', '28' ],
				[ 'Duits Tanzania', '27' ],
				[ 'Amerikaanse Filipijnen', '27' ],
				[ 'Deens Groenland', '26' ],
				[ 'Duits Kameroen', '26' ],
				[ 'Ottomaanse Rijk', '26' ],
				[ 'Portugees Mozambique', '25' ],
				[ 'Unie van Indochina', '25' ],
				[ 'Griekenland', '24' ],
				[ 'Republiek van Argentinië', '24' ],
				[ 'Mantsjoerije', '24' ],
				[ 'Russische Rijk', '23' ],
				[ 'Colombia', '22' ],
				[ 'Peru', '22' ],
				[ 'Republiek van Piratini', '22' ],
				[ 'Ecuador', '22' ],
				[ 'Siam', '21' ],
				[ 'Wit-Russische Republiek', '20' ],
				[ 'Abessinië', '20' ],
				[ 'Verenigde Staten van Brazilië', '19' ],
				[ 'Perzië', '19' ],
				[ 'Chinese Rijk', '19' ],
				[ 'Venezuela', '18' ],
				[ 'Siberië', '18' ],
				[ 'Ierland', '17' ],
				[ 'Republiek van Filipijns Moro', '17' ],
				[ 'Brits Nieuw-Zeeland', '17' ],
				[ 'Frankrijk', '15' ],
				[ 'Brits-India', '15' ],
				[ 'Confederale Staten van Amerika', '12' ],
				[ 'Brits Australië', '12' ],
				[ 'Baffin', '11' ],
				[ 'Kazachstan', '11' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Caribische Eilandenrepubliek', '10' ],
				[ 'Yakutia', '10' ],
				[ 'Het Duitse Rijk', '8' ],
				[ 'Australië', '8' ],
				[ 'Nepal', '4' ],
				[ 'Nederlands Nieuw-Guinea', '3' ],
				[ 'Spanje', '2' ],
				[ 'Schotland', '2' ],
				[ 'Frans West-Afrika', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Archangelsk', '1' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Koreaanse Rijk', '0' ]
			],
			[
				[ 'Italië', '62' ],
				[ 'Japanse rijk', '61' ],
				[ 'Arabië', '55' ],
				[ 'Verenigde Staten van Amerika', '52' ],
				[ 'Het Koninkrijk Engeland', '45' ],
				[ 'Frans Algerije', '43' ],
				[ 'Republiek Opper Volta', '43' ],
				[ 'Republiek China', '43' ],
				[ 'Zweden', '42' ],
				[ 'Duits Namibië', '41' ],
				[ 'Argentinië', '40' ],
				[ 'Papoea Nieuw-Guinese', '40' ],
				[ 'Brits Egypte', '39' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '38' ],
				[ 'Frans Madagascar', '38' ],
				[ 'Communistisch Rusland', '37' ],
				[ 'Frans Marokko', '35' ],
				[ 'Brits Canada', '34' ],
				[ 'Bolivia', '34' ],
				[ 'Anglo-Egyptisch Soedan', '34' ],
				[ 'Brits Birma', '34' ],
				[ 'Nederlands Oost-Indië', '34' ],
				[ 'Chili', '33' ],
				[ 'Brits Pakistan', '33' ],
				[ 'Duits Kameroen', '31' ],
				[ 'Duits Tanzania', '31' ],
				[ 'Republiek van Australië', '30' ],
				[ 'Unie van Indochina', '29' ],
				[ 'Portugees Mozambique', '28' ],
				[ 'Nederlands Indonesië', '28' ],
				[ 'Canada', '27' ],
				[ 'Deens Groenland', '27' ],
				[ 'Peru', '27' ],
				[ 'Ecuador', '25' ],
				[ 'Griekenland', '24' ],
				[ 'Mantsjoerije', '24' ],
				[ 'Republiek van Piratini', '23' ],
				[ 'Ottomaanse Rijk', '23' ],
				[ 'Siam', '23' ],
				[ 'Abessinië', '22' ],
				[ 'Chinees Sinkiang', '22' ],
				[ 'Amerikaanse Filipijnen', '22' ],
				[ 'Colombia', '21' ],
				[ 'Perzië', '20' ],
				[ 'Russische Rijk', '20' ],
				[ 'Chinese Rijk', '20' ],
				[ 'Venezuela', '18' ],
				[ 'Republiek van Argentinië', '17' ],
				[ 'Brits Nieuw-Zeeland', '17' ],
				[ 'Verenigde Staten van Brazilië', '16' ],
				[ 'Brits-India', '16' ],
				[ 'Siberië', '16' ],
				[ 'Republiek van Filipijns Moro', '16' ],
				[ 'Ierland', '15' ],
				[ 'Confederale Staten van Amerika', '13' ],
				[ 'Caribische Eilandenrepubliek', '12' ],
				[ 'Republiek Amazonas', '12' ],
				[ 'Wit-Russische Republiek', '11' ],
				[ 'Kazachstan', '11' ],
				[ 'Frankrijk', '10' ],
				[ 'Brits Australië', '10' ],
				[ 'Baffin', '9' ],
				[ 'Het Duitse Rijk', '7' ],
				[ 'Australië', '7' ],
				[ 'Nepal', '4' ],
				[ 'Yakutia', '3' ],
				[ 'Nederlands Nieuw-Guinea', '3' ],
				[ 'Spanje', '2' ],
				[ 'Schotland', '2' ],
				[ 'Archangelsk', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Frans West-Afrika', '1' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Koreaanse Rijk', '0' ]
			],
			[
				[ 'Japanse rijk', '63' ],
				[ 'Italië', '60' ],
				[ 'Verenigde Staten van Amerika', '55' ],
				[ 'Het Koninkrijk Engeland', '54' ],
				[ 'Arabië', '54' ],
				[ 'Frans Algerije', '50' ],
				[ 'Zweden', '46' ],
				[ 'Papoea Nieuw-Guinese', '44' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '43' ],
				[ 'Republiek Opper Volta', '43' ],
				[ 'Republiek China', '43' ],
				[ 'Duits Namibië', '41' ],
				[ 'Brits Egypte', '39' ],
				[ 'Communistisch Rusland', '38' ],
				[ 'Frans Madagascar', '37' ],
				[ 'Bolivia', '36' ],
				[ 'Duits Tanzania', '36' ],
				[ 'Nederlands Oost-Indië', '36' ],
				[ 'Brits Canada', '35' ],
				[ 'Argentinië', '35' ],
				[ 'Frans Marokko', '34' ],
				[ 'Chili', '33' ],
				[ 'Brits Birma', '33' ],
				[ 'Duits Kameroen', '32' ],
				[ 'Portugees Mozambique', '32' ],
				[ 'Brits Pakistan', '32' ],
				[ 'Peru', '31' ],
				[ 'Anglo-Egyptisch Soedan', '31' ],
				[ 'Unie van Indochina', '30' ],
				[ 'Republiek van Australië', '30' ],
				[ 'Nederlands Indonesië', '29' ],
				[ 'Ecuador', '28' ],
				[ 'Mantsjoerije', '28' ],
				[ 'Deens Groenland', '27' ],
				[ 'Canada', '26' ],
				[ 'Ottomaanse Rijk', '26' ],
				[ 'Chinees Sinkiang', '26' ],
				[ 'Griekenland', '24' ],
				[ 'Amerikaanse Filipijnen', '24' ],
				[ 'Siam', '23' ],
				[ 'Abessinië', '22' ],
				[ 'Chinese Rijk', '21' ],
				[ 'Perzië', '20' ],
				[ 'Venezuela', '19' ],
				[ 'Colombia', '19' ],
				[ 'Brits-India', '19' ],
				[ 'Republiek van Filipijns Moro', '18' ],
				[ 'Russische Rijk', '17' ],
				[ 'Ierland', '16' ],
				[ 'Brits Nieuw-Zeeland', '16' ],
				[ 'Republiek van Argentinië', '15' ],
				[ 'Republiek van Piratini', '15' ],
				[ 'Siberië', '15' ],
				[ 'Confederale Staten van Amerika', '13' ],
				[ 'Caribische Eilandenrepubliek', '13' ],
				[ 'Kazachstan', '13' ],
				[ 'Verenigde Staten van Brazilië', '12' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Het Duitse Rijk', '7' ],
				[ 'Australië', '5' ],
				[ 'Wit-Russische Republiek', '4' ],
				[ 'Nepal', '4' ],
				[ 'Brits Australië', '3' ],
				[ 'Nederlands Nieuw-Guinea', '3' ],
				[ 'Spanje', '2' ],
				[ 'Schotland', '2' ],
				[ 'Baffin', '2' ],
				[ 'Frans West-Afrika', '2' ],
				[ 'Yakutia', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Archangelsk', '1' ],
				[ 'Frankrijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Koreaanse Rijk', '0' ]
			],
			[
				[ 'Italië', '72' ],
				[ 'Japanse rijk', '64' ],
				[ 'Arabië', '61' ],
				[ 'Het Koninkrijk Engeland', '55' ],
				[ 'Frans Algerije', '52' ],
				[ 'Zweden', '51' ],
				[ 'Bolivia', '49' ],
				[ 'Verenigde Staten van Amerika', '45' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '44' ],
				[ 'Duits Namibië', '43' ],
				[ 'Republiek China', '43' ],
				[ 'Papoea Nieuw-Guinese', '43' ],
				[ 'Republiek Opper Volta', '42' ],
				[ 'Argentinië', '40' ],
				[ 'Brits Egypte', '38' ],
				[ 'Duits Tanzania', '38' ],
				[ 'Frans Madagascar', '38' ],
				[ 'Duits Kameroen', '37' ],
				[ 'Nederlands Oost-Indië', '35' ],
				[ 'Brits Canada', '34' ],
				[ 'Brits Birma', '34' ],
				[ 'Communistisch Rusland', '34' ],
				[ 'Frans Marokko', '33' ],
				[ 'Chili', '32' ],
				[ 'Portugees Mozambique', '32' ],
				[ 'Anglo-Egyptisch Soedan', '31' ],
				[ 'Brits Pakistan', '31' ],
				[ 'Mantsjoerije', '31' ],
				[ 'Republiek van Australië', '31' ],
				[ 'Nederlands Indonesië', '31' ],
				[ 'Peru', '30' ],
				[ 'Chinees Sinkiang', '28' ],
				[ 'Unie van Indochina', '27' ],
				[ 'Ottomaanse Rijk', '26' ],
				[ 'Amerikaanse Filipijnen', '26' ],
				[ 'Griekenland', '25' ],
				[ 'Canada', '25' ],
				[ 'Deens Groenland', '25' ],
				[ 'Venezuela', '25' ],
				[ 'Siam', '25' ],
				[ 'Chinese Rijk', '22' ],
				[ 'Ecuador', '21' ],
				[ 'Abessinië', '21' ],
				[ 'Colombia', '19' ],
				[ 'Perzië', '19' ],
				[ 'Brits-India', '19' ],
				[ 'Ierland', '18' ],
				[ 'Siberië', '16' ],
				[ 'Brits Nieuw-Zeeland', '16' ],
				[ 'Russische Rijk', '15' ],
				[ 'Kazachstan', '15' ],
				[ 'Republiek van Filipijns Moro', '15' ],
				[ 'Caribische Eilandenrepubliek', '14' ],
				[ 'Confederale Staten van Amerika', '13' ],
				[ 'Republiek van Argentinië', '13' ],
				[ 'Republiek Amazonas', '10' ],
				[ 'Het Duitse Rijk', '7' ],
				[ 'Australië', '4' ],
				[ 'Verenigde Staten van Brazilië', '3' ],
				[ 'Nepal', '3' ],
				[ 'Spanje', '2' ],
				[ 'Schotland', '2' ],
				[ 'Nederlands Nieuw-Guinea', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Baffin', '1' ],
				[ 'Frans West-Afrika', '1' ],
				[ 'Brits Australië', '1' ],
				[ 'Frankrijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Koreaanse Rijk', '0' ]
			],
			[
				[ 'Italië', '83' ],
				[ 'Zweden', '70' ],
				[ 'Japanse rijk', '70' ],
				[ 'Arabië', '60' ],
				[ 'Het Koninkrijk Engeland', '57' ],
				[ 'Frans Algerije', '55' ],
				[ 'Verenigde Staten van Amerika', '54' ],
				[ 'Republiek China', '48' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '46' ],
				[ 'Duits Namibië', '45' ],
				[ 'Papoea Nieuw-Guinese', '45' ],
				[ 'Republiek Opper Volta', '43' ],
				[ 'Bolivia', '42' ],
				[ 'Argentinië', '40' ],
				[ 'Brits Egypte', '40' ],
				[ 'Duits Tanzania', '40' ],
				[ 'Frans Madagascar', '40' ],
				[ 'Duits Kameroen', '39' ],
				[ 'Nederlands Oost-Indië', '38' ],
				[ 'Nederlands Indonesië', '36' ],
				[ 'Portugees Mozambique', '35' ],
				[ 'Frans Marokko', '34' ],
				[ 'Brits Birma', '34' ],
				[ 'Brits Canada', '33' ],
				[ 'Mantsjoerije', '33' ],
				[ 'Republiek van Australië', '33' ],
				[ 'Anglo-Egyptisch Soedan', '32' ],
				[ 'Brits Pakistan', '32' ],
				[ 'Unie van Indochina', '30' ],
				[ 'Chinees Sinkiang', '30' ],
				[ 'Venezuela', '28' ],
				[ 'Chili', '28' ],
				[ 'Siam', '27' ],
				[ 'Amerikaanse Filipijnen', '27' ],
				[ 'Deens Groenland', '26' ],
				[ 'Canada', '25' ],
				[ 'Abessinië', '25' ],
				[ 'Griekenland', '24' ],
				[ 'Peru', '23' ],
				[ 'Colombia', '21' ],
				[ 'Ierland', '20' ],
				[ 'Chinese Rijk', '20' ],
				[ 'Brits-India', '19' ],
				[ 'Siberië', '18' ],
				[ 'Kazachstan', '17' ],
				[ 'Confederale Staten van Amerika', '15' ],
				[ 'Caribische Eilandenrepubliek', '14' ],
				[ 'Russische Rijk', '14' ],
				[ 'Republiek van Argentinië', '13' ],
				[ 'Ottomaanse Rijk', '13' ],
				[ 'Brits Nieuw-Zeeland', '12' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Republiek van Filipijns Moro', '10' ],
				[ 'Ecuador', '9' ],
				[ 'Communistisch Rusland', '8' ],
				[ 'Het Duitse Rijk', '6' ],
				[ 'Australië', '4' ],
				[ 'Nepal', '4' ],
				[ 'Perzië', '3' ],
				[ 'Spanje', '2' ],
				[ 'Schotland', '2' ],
				[ 'Brits Australië', '2' ],
				[ 'Nederlands Nieuw-Guinea', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Verenigde Staten van Brazilië', '1' ],
				[ 'Frans West-Afrika', '1' ],
				[ 'Frankrijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Koreaanse Rijk', '0' ]
			],
			[
				[ 'Italië', '92' ],
				[ 'Zweden', '74' ],
				[ 'Japanse rijk', '73' ],
				[ 'Het Koninkrijk Engeland', '58' ],
				[ 'Frans Algerije', '57' ],
				[ 'Arabië', '57' ],
				[ 'Republiek Opper Volta', '55' ],
				[ 'Verenigde Staten van Amerika', '50' ],
				[ 'Republiek China', '50' ],
				[ 'Papoea Nieuw-Guinese', '47' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '46' ],
				[ 'Duits Namibië', '45' ],
				[ 'Brits Egypte', '42' ],
				[ 'Duits Tanzania', '42' ],
				[ 'Argentinië', '41' ],
				[ 'Frans Madagascar', '41' ],
				[ 'Duits Kameroen', '40' ],
				[ 'Portugees Mozambique', '38' ],
				[ 'Nederlands Indonesië', '38' ],
				[ 'Nederlands Oost-Indië', '36' ],
				[ 'Anglo-Egyptisch Soedan', '34' ],
				[ 'Republiek van Australië', '34' ],
				[ 'Brits Canada', '33' ],
				[ 'Mantsjoerije', '33' ],
				[ 'Brits Birma', '32' ],
				[ 'Chili', '31' ],
				[ 'Bolivia', '31' ],
				[ 'Brits Pakistan', '31' ],
				[ 'Chinees Sinkiang', '31' ],
				[ 'Venezuela', '30' ],
				[ 'Frans Marokko', '30' ],
				[ 'Unie van Indochina', '30' ],
				[ 'Peru', '29' ],
				[ 'Abessinië', '28' ],
				[ 'Amerikaanse Filipijnen', '27' ],
				[ 'Deens Groenland', '26' ],
				[ 'Canada', '24' ],
				[ 'Griekenland', '22' ],
				[ 'Brits-India', '21' ],
				[ 'Siam', '21' ],
				[ 'Chinese Rijk', '20' ],
				[ 'Ierland', '19' ],
				[ 'Kazachstan', '19' ],
				[ 'Colombia', '18' ],
				[ 'Siberië', '18' ],
				[ 'Confederale Staten van Amerika', '17' ],
				[ 'Caribische Eilandenrepubliek', '14' ],
				[ 'Republiek van Argentinië', '14' ],
				[ 'Ottomaanse Rijk', '12' ],
				[ 'Russische Rijk', '12' ],
				[ 'Brits Nieuw-Zeeland', '11' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Ecuador', '8' ],
				[ 'Het Duitse Rijk', '6' ],
				[ 'Communistisch Rusland', '4' ],
				[ 'Nepal', '4' ],
				[ 'Spanje', '3' ],
				[ 'Australië', '3' ],
				[ 'Schotland', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Perzië', '1' ],
				[ 'Republiek van Filipijns Moro', '1' ],
				[ 'Frankrijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Italië', '94' ],
				[ 'Zweden', '78' ],
				[ 'Arabië', '76' ],
				[ 'Japanse rijk', '69' ],
				[ 'Het Koninkrijk Engeland', '63' ],
				[ 'Frans Algerije', '57' ],
				[ 'Papoea Nieuw-Guinese', '55' ],
				[ 'Republiek Opper Volta', '54' ],
				[ 'Republiek China', '53' ],
				[ 'Verenigde Staten van Amerika', '52' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '49' ],
				[ 'Duits Tanzania', '47' ],
				[ 'Frans Madagascar', '43' ],
				[ 'Nederlands Indonesië', '43' ],
				[ 'Argentinië', '39' ],
				[ 'Portugees Mozambique', '39' ],
				[ 'Nederlands Oost-Indië', '38' ],
				[ 'Duits Kameroen', '37' ],
				[ 'Venezuela', '36' ],
				[ 'Brits Birma', '36' ],
				[ 'Republiek van Australië', '36' ],
				[ 'Anglo-Egyptisch Soedan', '35' ],
				[ 'Mantsjoerije', '35' ],
				[ 'Brits Canada', '34' ],
				[ 'Brits Egypte', '34' ],
				[ 'Chili', '33' ],
				[ 'Peru', '32' ],
				[ 'Unie van Indochina', '32' ],
				[ 'Brits Pakistan', '32' ],
				[ 'Chinees Sinkiang', '30' ],
				[ 'Abessinië', '29' ],
				[ 'Deens Groenland', '28' ],
				[ 'Frans Marokko', '26' ],
				[ 'Griekenland', '24' ],
				[ 'Canada', '24' ],
				[ 'Brits-India', '23' ],
				[ 'Siberië', '21' ],
				[ 'Kazachstan', '21' ],
				[ 'Amerikaanse Filipijnen', '21' ],
				[ 'Ierland', '20' ],
				[ 'Chinese Rijk', '19' ],
				[ 'Siam', '18' ],
				[ 'Colombia', '17' ],
				[ 'Confederale Staten van Amerika', '16' ],
				[ 'Caribische Eilandenrepubliek', '15' ],
				[ 'Brits Nieuw-Zeeland', '14' ],
				[ 'Republiek van Argentinië', '13' ],
				[ 'Duits Namibië', '13' ],
				[ 'Ottomaanse Rijk', '13' ],
				[ 'Russische Rijk', '11' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Bolivia', '9' ],
				[ 'Ecuador', '8' ],
				[ 'Het Duitse Rijk', '6' ],
				[ 'Nepal', '4' ],
				[ 'Spanje', '2' ],
				[ 'Australië', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Schotland', '1' ],
				[ 'Communistisch Rusland', '1' ],
				[ 'Frankrijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Perzië', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Italië', '104' ],
				[ 'Arabië', '91' ],
				[ 'Zweden', '88' ],
				[ 'Japanse rijk', '85' ],
				[ 'Het Koninkrijk Engeland', '66' ],
				[ 'Frans Algerije', '60' ],
				[ 'Papoea Nieuw-Guinese', '60' ],
				[ 'Verenigde Staten van Amerika', '57' ],
				[ 'Republiek Opper Volta', '57' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '48' ],
				[ 'Duits Tanzania', '45' ],
				[ 'Nederlands Indonesië', '45' ],
				[ 'Frans Madagascar', '44' ],
				[ 'Republiek China', '42' ],
				[ 'Nederlands Oost-Indië', '41' ],
				[ 'Venezuela', '39' ],
				[ 'Portugees Mozambique', '39' ],
				[ 'Republiek van Australië', '39' ],
				[ 'Argentinië', '38' ],
				[ 'Chili', '38' ],
				[ 'Anglo-Egyptisch Soedan', '37' ],
				[ 'Mantsjoerije', '37' ],
				[ 'Brits Canada', '36' ],
				[ 'Brits Birma', '35' ],
				[ 'Peru', '32' ],
				[ 'Abessinië', '31' ],
				[ 'Unie van Indochina', '31' ],
				[ 'Brits Pakistan', '31' ],
				[ 'Chinees Sinkiang', '31' ],
				[ 'Brits Egypte', '30' ],
				[ 'Duits Kameroen', '30' ],
				[ 'Deens Groenland', '29' ],
				[ 'Canada', '27' ],
				[ 'Griekenland', '24' ],
				[ 'Kazachstan', '24' ],
				[ 'Brits-India', '23' ],
				[ 'Frans Marokko', '22' ],
				[ 'Ierland', '20' ],
				[ 'Siberië', '20' ],
				[ 'Chinese Rijk', '20' ],
				[ 'Duits Namibië', '18' ],
				[ 'Confederale Staten van Amerika', '17' ],
				[ 'Siam', '14' ],
				[ 'Brits Nieuw-Zeeland', '14' ],
				[ 'Republiek Amazonas', '13' ],
				[ 'Colombia', '11' ],
				[ 'Republiek van Argentinië', '11' ],
				[ 'Russische Rijk', '11' ],
				[ 'Ecuador', '7' ],
				[ 'Het Duitse Rijk', '5' ],
				[ 'Caribische Eilandenrepubliek', '4' ],
				[ 'Nepal', '3' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Spanje', '1' ],
				[ 'Schotland', '1' ],
				[ 'Bolivia', '1' ],
				[ 'Australië', '1' ],
				[ 'Frankrijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Italië', '111' ],
				[ 'Japanse rijk', '108' ],
				[ 'Zweden', '98' ],
				[ 'Arabië', '97' ],
				[ 'Het Koninkrijk Engeland', '70' ],
				[ 'Frans Algerije', '69' ],
				[ 'Verenigde Staten van Amerika', '62' ],
				[ 'Papoea Nieuw-Guinese', '60' ],
				[ 'Republiek Opper Volta', '55' ],
				[ 'Argentinië', '53' ],
				[ 'Republiek van Australië', '49' ],
				[ 'Nederlands Indonesië', '48' ],
				[ 'Nederlands Oost-Indië', '47' ],
				[ 'Frans Madagascar', '44' ],
				[ 'Venezuela', '42' ],
				[ 'Brits Canada', '41' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '41' ],
				[ 'Duits Tanzania', '40' ],
				[ 'Chili', '39' ],
				[ 'Anglo-Egyptisch Soedan', '39' ],
				[ 'Brits Birma', '36' ],
				[ 'Deens Groenland', '34' ],
				[ 'Abessinië', '33' ],
				[ 'Portugees Mozambique', '33' ],
				[ 'Peru', '32' ],
				[ 'Brits Egypte', '32' ],
				[ 'Unie van Indochina', '32' ],
				[ 'Brits Pakistan', '32' ],
				[ 'Chinees Sinkiang', '31' ],
				[ 'Canada', '30' ],
				[ 'Griekenland', '29' ],
				[ 'Duits Kameroen', '28' ],
				[ 'Kazachstan', '27' ],
				[ 'Brits-India', '25' ],
				[ 'Chinese Rijk', '23' ],
				[ 'Ierland', '22' ],
				[ 'Brits Nieuw-Zeeland', '19' ],
				[ 'Confederale Staten van Amerika', '17' ],
				[ 'Siberië', '17' ],
				[ 'Duits Namibië', '16' ],
				[ 'Republiek China', '15' ],
				[ 'Republiek Amazonas', '13' ],
				[ 'Russische Rijk', '10' ],
				[ 'Mantsjoerije', '9' ],
				[ 'Ecuador', '8' ],
				[ 'Siam', '7' ],
				[ 'Het Duitse Rijk', '4' ],
				[ 'Frans Marokko', '3' ],
				[ 'Nepal', '3' ],
				[ 'Colombia', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Spanje', '1' ],
				[ 'Schotland', '1' ],
				[ 'Republiek van Argentinië', '1' ],
				[ 'Frankrijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Caribische Eilandenrepubliek', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Bolivia', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Australië', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Italië', '135' ],
				[ 'Japanse rijk', '114' ],
				[ 'Arabië', '105' ],
				[ 'Zweden', '102' ],
				[ 'Frans Algerije', '92' ],
				[ 'Het Koninkrijk Engeland', '64' ],
				[ 'Verenigde Staten van Amerika', '61' ],
				[ 'Papoea Nieuw-Guinese', '59' ],
				[ 'Republiek Opper Volta', '58' ],
				[ 'Nederlands Oost-Indië', '57' ],
				[ 'Argentinië', '54' ],
				[ 'Republiek van Australië', '52' ],
				[ 'Nederlands Indonesië', '49' ],
				[ 'Venezuela', '45' ],
				[ 'Chili', '45' ],
				[ 'Brits Canada', '44' ],
				[ 'Duits Tanzania', '43' ],
				[ 'Anglo-Egyptisch Soedan', '40' ],
				[ 'Deens Groenland', '36' ],
				[ 'Brits Birma', '36' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '35' ],
				[ 'Abessinië', '34' ],
				[ 'Peru', '32' ],
				[ 'Unie van Indochina', '32' ],
				[ 'Chinees Sinkiang', '32' ],
				[ 'Canada', '31' ],
				[ 'Brits Egypte', '31' ],
				[ 'Griekenland', '30' ],
				[ 'Kazachstan', '29' ],
				[ 'Brits Pakistan', '28' ],
				[ 'Duits Kameroen', '27' ],
				[ 'Chinese Rijk', '27' ],
				[ 'Brits-India', '26' ],
				[ 'Frans Madagascar', '25' ],
				[ 'Ierland', '21' ],
				[ 'Portugees Mozambique', '21' ],
				[ 'Confederale Staten van Amerika', '17' ],
				[ 'Siberië', '16' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Duits Namibië', '10' ],
				[ 'Russische Rijk', '9' ],
				[ 'Ecuador', '7' ],
				[ 'Brits Nieuw-Zeeland', '6' ],
				[ 'Republiek China', '5' ],
				[ 'Mantsjoerije', '4' ],
				[ 'Nepal', '3' ],
				[ 'Schotland', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Spanje', '1' ],
				[ 'Het Duitse Rijk', '1' ],
				[ 'Colombia', '1' ],
				[ 'Frankrijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Caribische Eilandenrepubliek', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Argentinië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Bolivia', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Frans Marokko', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Siam', '0' ],
				[ 'Australië', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Italië', '146' ],
				[ 'Japanse rijk', '125' ],
				[ 'Arabië', '108' ],
				[ 'Zweden', '107' ],
				[ 'Frans Algerije', '97' ],
				[ 'Het Koninkrijk Engeland', '74' ],
				[ 'Verenigde Staten van Amerika', '65' ],
				[ 'Papoea Nieuw-Guinese', '63' ],
				[ 'Nederlands Oost-Indië', '60' ],
				[ 'Argentinië', '59' ],
				[ 'Republiek Opper Volta', '58' ],
				[ 'Republiek van Australië', '55' ],
				[ 'Nederlands Indonesië', '51' ],
				[ 'Brits Canada', '49' ],
				[ 'Chili', '46' ],
				[ 'Duits Tanzania', '45' ],
				[ 'Anglo-Egyptisch Soedan', '41' ],
				[ 'Deens Groenland', '36' ],
				[ 'Brits Birma', '35' ],
				[ 'Canada', '31' ],
				[ 'Brits Pakistan', '31' ],
				[ 'Chinees Sinkiang', '31' ],
				[ 'Kazachstan', '31' ],
				[ 'Griekenland', '30' ],
				[ 'Peru', '30' ],
				[ 'Duits Kameroen', '30' ],
				[ 'Abessinië', '29' ],
				[ 'Brits Egypte', '28' ],
				[ 'Chinese Rijk', '28' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '27' ],
				[ 'Brits-India', '27' ],
				[ 'Venezuela', '26' ],
				[ 'Unie van Indochina', '26' ],
				[ 'Frans Madagascar', '25' ],
				[ 'Ierland', '20' ],
				[ 'Portugees Mozambique', '18' ],
				[ 'Confederale Staten van Amerika', '15' ],
				[ 'Siberië', '15' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Russische Rijk', '10' ],
				[ 'Ecuador', '7' ],
				[ 'Duits Namibië', '5' ],
				[ 'Brits Nieuw-Zeeland', '5' ],
				[ 'Nepal', '3' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Republiek China', '1' ],
				[ 'Spanje', '0' ],
				[ 'Frankrijk', '0' ],
				[ 'Het Duitse Rijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Schotland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Caribische Eilandenrepubliek', '0' ],
				[ 'Colombia', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Argentinië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Bolivia', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Frans Marokko', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Mantsjoerije', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Siam', '0' ],
				[ 'Australië', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Italië', '148' ],
				[ 'Japanse rijk', '140' ],
				[ 'Arabië', '113' ],
				[ 'Zweden', '112' ],
				[ 'Frans Algerije', '98' ],
				[ 'Het Koninkrijk Engeland', '81' ],
				[ 'Argentinië', '75' ],
				[ 'Verenigde Staten van Amerika', '72' ],
				[ 'Papoea Nieuw-Guinese', '65' ],
				[ 'Nederlands Oost-Indië', '61' ],
				[ 'Republiek Opper Volta', '58' ],
				[ 'Republiek van Australië', '57' ],
				[ 'Brits Canada', '52' ],
				[ 'Chili', '51' ],
				[ 'Duits Tanzania', '46' ],
				[ 'Anglo-Egyptisch Soedan', '42' ],
				[ 'Deens Groenland', '38' ],
				[ 'Nederlands Indonesië', '37' ],
				[ 'Duits Kameroen', '34' ],
				[ 'Brits Birma', '34' ],
				[ 'Abessinië', '33' ],
				[ 'Canada', '32' ],
				[ 'Peru', '31' ],
				[ 'Brits Pakistan', '31' ],
				[ 'Chinees Sinkiang', '31' ],
				[ 'Kazachstan', '31' ],
				[ 'Brits-India', '30' ],
				[ 'Brits Egypte', '29' ],
				[ 'Griekenland', '26' ],
				[ 'Chinese Rijk', '26' ],
				[ 'Unie van Indochina', '25' ],
				[ 'Frans Madagascar', '20' ],
				[ 'Ierland', '19' ],
				[ 'Confederale Staten van Amerika', '16' ],
				[ 'Siberië', '16' ],
				[ 'Russische Rijk', '13' ],
				[ 'Republiek Amazonas', '13' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '7' ],
				[ 'Ecuador', '7' ],
				[ 'Portugees Mozambique', '6' ],
				[ 'Brits Nieuw-Zeeland', '5' ],
				[ 'Duits Namibië', '3' ],
				[ 'Venezuela', '2' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Nepal', '2' ],
				[ 'Spanje', '0' ],
				[ 'Frankrijk', '0' ],
				[ 'Het Duitse Rijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Schotland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Caribische Eilandenrepubliek', '0' ],
				[ 'Colombia', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Argentinië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Bolivia', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Frans Marokko', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Mantsjoerije', '0' ],
				[ 'Republiek China', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Siam', '0' ],
				[ 'Australië', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Japanse rijk', '151' ],
				[ 'Italië', '148' ],
				[ 'Arabië', '126' ],
				[ 'Zweden', '117' ],
				[ 'Frans Algerije', '104' ],
				[ 'Het Koninkrijk Engeland', '92' ],
				[ 'Argentinië', '85' ],
				[ 'Verenigde Staten van Amerika', '75' ],
				[ 'Papoea Nieuw-Guinese', '69' ],
				[ 'Brits Canada', '60' ],
				[ 'Republiek Opper Volta', '60' ],
				[ 'Republiek van Australië', '60' ],
				[ 'Chili', '54' ],
				[ 'Duits Tanzania', '48' ],
				[ 'Duits Kameroen', '46' ],
				[ 'Anglo-Egyptisch Soedan', '43' ],
				[ 'Deens Groenland', '38' ],
				[ 'Nederlands Indonesië', '35' ],
				[ 'Brits Birma', '34' ],
				[ 'Abessinië', '32' ],
				[ 'Canada', '31' ],
				[ 'Brits Egypte', '31' ],
				[ 'Peru', '30' ],
				[ 'Brits Pakistan', '30' ],
				[ 'Kazachstan', '30' ],
				[ 'Brits-India', '29' ],
				[ 'Griekenland', '27' ],
				[ 'Unie van Indochina', '27' ],
				[ 'Chinese Rijk', '27' ],
				[ 'Chinees Sinkiang', '25' ],
				[ 'Nederlands Oost-Indië', '22' ],
				[ 'Confederale Staten van Amerika', '21' ],
				[ 'Siberië', '19' ],
				[ 'Russische Rijk', '15' ],
				[ 'Republiek Amazonas', '13' ],
				[ 'Ecuador', '7' ],
				[ 'Portugees Mozambique', '6' ],
				[ 'Frans Madagascar', '6' ],
				[ 'Duits Namibië', '2' ],
				[ 'Nepal', '2' ],
				[ 'Ierland', '1' ],
				[ 'Brits Kashmir', '1' ],
				[ 'Spanje', '0' ],
				[ 'Frankrijk', '0' ],
				[ 'Het Duitse Rijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Schotland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
				[ 'Caribische Eilandenrepubliek', '0' ],
				[ 'Venezuela', '0' ],
				[ 'Colombia', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Argentinië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Bolivia', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Frans Marokko', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Mantsjoerije', '0' ],
				[ 'Republiek China', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Siam', '0' ],
				[ 'Australië', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Brits Nieuw-Zeeland', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Japanse rijk', '176' ],
				[ 'Italië', '149' ],
				[ 'Arabië', '130' ],
				[ 'Zweden', '119' ],
				[ 'Frans Algerije', '112' ],
				[ 'Het Koninkrijk Engeland', '95' ],
				[ 'Argentinië', '82' ],
				[ 'Papoea Nieuw-Guinese', '81' ],
				[ 'Verenigde Staten van Amerika', '67' ],
				[ 'Republiek van Australië', '59' ],
				[ 'Republiek Opper Volta', '58' ],
				[ 'Brits Canada', '57' ],
				[ 'Chili', '57' ],
				[ 'Duits Tanzania', '50' ],
				[ 'Duits Kameroen', '47' ],
				[ 'Anglo-Egyptisch Soedan', '41' ],
				[ 'Deens Groenland', '38' ],
				[ 'Brits Egypte', '38' ],
				[ 'Brits Birma', '33' ],
				[ 'Canada', '31' ],
				[ 'Abessinië', '30' ],
				[ 'Unie van Indochina', '29' ],
				[ 'Brits Pakistan', '29' ],
				[ 'Brits-India', '29' ],
				[ 'Kazachstan', '29' ],
				[ 'Peru', '28' ],
				[ 'Chinees Sinkiang', '28' ],
				[ 'Chinese Rijk', '28' ],
				[ 'Nederlands Oost-Indië', '27' ],
				[ 'Confederale Staten van Amerika', '23' ],
				[ 'Siberië', '20' ],
				[ 'Griekenland', '16' ],
				[ 'Russische Rijk', '16' ],
				[ 'Nederlands Indonesië', '11' ],
				[ 'Republiek Amazonas', '11' ],
				[ 'Ecuador', '6' ],
				[ 'Portugees Mozambique', '4' ],
				[ 'Frans Madagascar', '4' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Nepal', '2' ],
				[ 'Duits Namibië', '1' ],
				[ 'Spanje', '0' ],
				[ 'Frankrijk', '0' ],
				[ 'Het Duitse Rijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Schotland', '0' ],
				[ 'Ierland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
				[ 'Caribische Eilandenrepubliek', '0' ],
				[ 'Venezuela', '0' ],
				[ 'Colombia', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Argentinië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Bolivia', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Frans Marokko', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Mantsjoerije', '0' ],
				[ 'Republiek China', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Siam', '0' ],
				[ 'Australië', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Brits Nieuw-Zeeland', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Japanse rijk', '175' ],
				[ 'Italië', '146' ],
				[ 'Arabië', '122' ],
				[ 'Zweden', '119' ],
				[ 'Frans Algerije', '113' ],
				[ 'Het Koninkrijk Engeland', '95' ],
				[ 'Papoea Nieuw-Guinese', '83' ],
				[ 'Argentinië', '82' ],
				[ 'Verenigde Staten van Amerika', '75' ],
				[ 'Duits Tanzania', '62' ],
				[ 'Republiek van Australië', '62' ],
				[ 'Chili', '61' ],
				[ 'Brits Canada', '57' ],
				[ 'Republiek Opper Volta', '56' ],
				[ 'Duits Kameroen', '41' ],
				[ 'Brits Egypte', '40' ],
				[ 'Anglo-Egyptisch Soedan', '40' ],
				[ 'Deens Groenland', '39' ],
				[ 'Brits Birma', '31' ],
				[ 'Canada', '30' ],
				[ 'Brits-India', '30' ],
				[ 'Abessinië', '29' ],
				[ 'Unie van Indochina', '28' ],
				[ 'Brits Pakistan', '28' ],
				[ 'Chinees Sinkiang', '28' ],
				[ 'Kazachstan', '28' ],
				[ 'Chinese Rijk', '28' ],
				[ 'Peru', '27' ],
				[ 'Nederlands Oost-Indië', '26' ],
				[ 'Confederale Staten van Amerika', '24' ],
				[ 'Siberië', '21' ],
				[ 'Russische Rijk', '17' ],
				[ 'Frans Madagascar', '14' ],
				[ 'Griekenland', '13' ],
				[ 'Republiek Amazonas', '12' ],
				[ 'Ecuador', '6' ],
				[ 'Nederlands Indonesië', '3' ],
				[ 'Brits Kashmir', '2' ],
				[ 'Nepal', '2' ],
				[ 'Portugees Mozambique', '1' ],
				[ 'Spanje', '0' ],
				[ 'Frankrijk', '0' ],
				[ 'Het Duitse Rijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Schotland', '0' ],
				[ 'Ierland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
				[ 'Caribische Eilandenrepubliek', '0' ],
				[ 'Venezuela', '0' ],
				[ 'Colombia', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Argentinië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Bolivia', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Duits Namibië', '0' ],
				[ 'Frans Marokko', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Mantsjoerije', '0' ],
				[ 'Republiek China', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Siam', '0' ],
				[ 'Australië', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Brits Nieuw-Zeeland', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
			[
				[ 'Japanse rijk', '176' ],
				[ 'Italië', '165' ],
				[ 'Zweden', '125' ],
				[ 'Arabië', '125' ],
				[ 'Frans Algerije', '112' ],
				[ 'Het Koninkrijk Engeland', '98' ],
				[ 'Argentinië', '85' ],
				[ 'Papoea Nieuw-Guinese', '80' ],
				[ 'Duits Tanzania', '70' ],
				[ 'Verenigde Staten van Amerika', '68' ],
				[ 'Chili', '65' ],
				[ 'Republiek van Australië', '65' ],
				[ 'Brits Canada', '53' ],
				[ 'Deens Groenland', '43' ],
				[ 'Brits Egypte', '42' ],
				[ 'Duits Kameroen', '40' ],
				[ 'Republiek Opper Volta', '40' ],
				[ 'Anglo-Egyptisch Soedan', '39' ],
				[ 'Canada', '31' ],
				[ 'Brits Birma', '31' ],
				[ 'Brits-India', '30' ],
				[ 'Nederlands Oost-Indië', '29' ],
				[ 'Peru', '28' ],
				[ 'Unie van Indochina', '28' ],
				[ 'Brits Pakistan', '28' ],
				[ 'Chinees Sinkiang', '28' ],
				[ 'Kazachstan', '28' ],
				[ 'Chinese Rijk', '28' ],
				[ 'Siberië', '21' ],
				[ 'Confederale Staten van Amerika', '20' ],
				[ 'Russische Rijk', '18' ],
				[ 'Abessinië', '17' ],
				[ 'Frans Madagascar', '17' ],
				[ 'Republiek Amazonas', '10' ],
				[ 'Ecuador', '7' ],
				[ 'Griekenland', '4' ],
				[ 'Nepal', '2' ],
				[ 'Brits Kashmir', '1' ],
				[ 'Spanje', '0' ],
				[ 'Frankrijk', '0' ],
				[ 'Het Duitse Rijk', '0' ],
				[ 'Oostenrijk-Hongarije', '0' ],
				[ 'Noorwegen', '0' ],
				[ 'Finland', '0' ],
				[ 'Schotland', '0' ],
				[ 'Ierland', '0' ],
				[ 'Wit-Russische Republiek', '0' ],
				[ 'Baffin', '0' ],
				[ 'Federale Staten van Amerika', '0' ],
				[ 'Mexico', '0' ],
				[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
				[ 'Caribische Eilandenrepubliek', '0' ],
				[ 'Venezuela', '0' ],
				[ 'Colombia', '0' ],
				[ 'Verenigde Staten van Brazilië', '0' ],
				[ 'Republiek van Argentinië', '0' ],
				[ 'Republiek van Piratini', '0' ],
				[ 'Bolivia', '0' ],
				[ 'Frans West-Afrika', '0' ],
				[ 'Unie van Zuid-Afrika', '0' ],
				[ 'Belgisch Congo', '0' ],
				[ 'Duits Namibië', '0' ],
				[ 'Portugees Mozambique', '0' ],
				[ 'Frans Marokko', '0' ],
				[ 'Perzië', '0' ],
				[ 'Ottomaanse Rijk', '0' ],
				[ 'Communistisch Rusland', '0' ],
				[ 'Yakutia', '0' ],
				[ 'Archangelsk', '0' ],
				[ 'Mantsjoerije', '0' ],
				[ 'Republiek China', '0' ],
				[ 'Koreaanse Rijk', '0' ],
				[ 'Siam', '0' ],
				[ 'Australië', '0' ],
				[ 'Brits Australië', '0' ],
				[ 'Nederlands Indonesië', '0' ],
				[ 'Amerikaanse Filipijnen', '0' ],
				[ 'Republiek van Filipijns Moro', '0' ],
				[ 'Brits Nieuw-Zeeland', '0' ],
				[ 'Nederlands Nieuw-Guinea', '0' ]
			],
	[
		[ 'Japanse rijk', '180' ],
		[ 'Italië', '167' ],
		[ 'Zweden', '126' ],
		[ 'Arabië', '126' ],
		[ 'Frans Algerije', '116' ],
		[ 'Het Koninkrijk Engeland', '99' ],
		[ 'Argentinië', '86' ],
		[ 'Papoea Nieuw-Guinese', '80' ],
		[ 'Duits Tanzania', '74' ],
		[ 'Verenigde Staten van Amerika', '69' ],
		[ 'Chili', '67' ],
		[ 'Republiek van Australië', '67' ],
		[ 'Brits Canada', '49' ],
		[ 'Deens Groenland', '44' ],
		[ 'Duits Kameroen', '43' ],
		[ 'Brits Egypte', '42' ],
		[ 'Anglo-Egyptisch Soedan', '40' ],
		[ 'Nederlands Oost-Indië', '33' ],
		[ 'Canada', '32' ],
		[ 'Brits Birma', '31' ],
		[ 'Brits-India', '31' ],
		[ 'Peru', '28' ],
		[ 'Republiek Opper Volta', '28' ],
		[ 'Chinees Sinkiang', '28' ],
		[ 'Kazachstan', '28' ],
		[ 'Unie van Indochina', '27' ],
		[ 'Chinese Rijk', '27' ],
		[ 'Brits Pakistan', '21' ],
		[ 'Russische Rijk', '19' ],
		[ 'Confederale Staten van Amerika', '18' ],
		[ 'Abessinië', '18' ],
		[ 'Frans Madagascar', '18' ],
		[ 'Siberië', '18' ],
		[ 'Republiek Amazonas', '9' ],
		[ 'Ecuador', '7' ],
		[ 'Griekenland', '3' ],
		[ 'Nepal', '2' ],
		[ 'Brits Kashmir', '1' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Japanse rijk', '183' ],
		[ 'Italië', '167' ],
		[ 'Frans Algerije', '132' ],
		[ 'Zweden', '125' ],
		[ 'Arabië', '124' ],
		[ 'Het Koninkrijk Engeland', '99' ],
		[ 'Argentinië', '87' ],
		[ 'Papoea Nieuw-Guinese', '81' ],
		[ 'Duits Tanzania', '77' ],
		[ 'Verenigde Staten van Amerika', '69' ],
		[ 'Republiek van Australië', '68' ],
		[ 'Chili', '67' ],
		[ 'Duits Kameroen', '61' ],
		[ 'Brits Canada', '45' ],
		[ 'Brits Egypte', '42' ],
		[ 'Deens Groenland', '41' ],
		[ 'Nederlands Oost-Indië', '40' ],
		[ 'Anglo-Egyptisch Soedan', '39' ],
		[ 'Canada', '33' ],
		[ 'Brits Birma', '30' ],
		[ 'Brits-India', '30' ],
		[ 'Peru', '27' ],
		[ 'Unie van Indochina', '27' ],
		[ 'Chinees Sinkiang', '27' ],
		[ 'Kazachstan', '27' ],
		[ 'Chinese Rijk', '27' ],
		[ 'Frans Madagascar', '22' ],
		[ 'Siberië', '20' ],
		[ 'Brits Pakistan', '19' ],
		[ 'Confederale Staten van Amerika', '17' ],
		[ 'Russische Rijk', '17' ],
		[ 'Abessinië', '14' ],
		[ 'Republiek Opper Volta', '9' ],
		[ 'Republiek Amazonas', '9' ],
		[ 'Ecuador', '7' ],
		[ 'Nepal', '2' ],
		[ 'Brits Kashmir', '1' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Japanse rijk', '191' ],
		[ 'Italië', '157' ],
		[ 'Frans Algerije', '147' ],
		[ 'Zweden', '128' ],
		[ 'Arabië', '122' ],
		[ 'Het Koninkrijk Engeland', '102' ],
		[ 'Argentinië', '89' ],
		[ 'Duits Tanzania', '83' ],
		[ 'Papoea Nieuw-Guinese', '83' ],
		[ 'Verenigde Staten van Amerika', '73' ],
		[ 'Republiek van Australië', '70' ],
		[ 'Chili', '64' ],
		[ 'Duits Kameroen', '62' ],
		[ 'Nederlands Oost-Indië', '47' ],
		[ 'Brits Canada', '46' ],
		[ 'Brits Egypte', '43' ],
		[ 'Anglo-Egyptisch Soedan', '40' ],
		[ 'Deens Groenland', '37' ],
		[ 'Canada', '35' ],
		[ 'Unie van Indochina', '27' ],
		[ 'Kazachstan', '27' ],
		[ 'Peru', '26' ],
		[ 'Chinees Sinkiang', '26' ],
		[ 'Brits-India', '25' ],
		[ 'Brits Birma', '24' ],
		[ 'Chinese Rijk', '24' ],
		[ 'Frans Madagascar', '22' ],
		[ 'Siberië', '22' ],
		[ 'Brits Pakistan', '20' ],
		[ 'Confederale Staten van Amerika', '16' ],
		[ 'Republiek Amazonas', '10' ],
		[ 'Russische Rijk', '9' ],
		[ 'Ecuador', '7' ],
		[ 'Abessinië', '6' ],
		[ 'Nepal', '2' ],
		[ 'Brits Kashmir', '1' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Republiek Opper Volta', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Japanse rijk', '197' ],
		[ 'Italië', '167' ],
		[ 'Frans Algerije', '148' ],
		[ 'Zweden', '127' ],
		[ 'Arabië', '117' ],
		[ 'Het Koninkrijk Engeland', '101' ],
		[ 'Argentinië', '89' ],
		[ 'Duits Tanzania', '88' ],
		[ 'Papoea Nieuw-Guinese', '84' ],
		[ 'Verenigde Staten van Amerika', '74' ],
		[ 'Republiek van Australië', '74' ],
		[ 'Chili', '64' ],
		[ 'Duits Kameroen', '62' ],
		[ 'Nederlands Oost-Indië', '62' ],
		[ 'Brits Canada', '45' ],
		[ 'Brits Egypte', '42' ],
		[ 'Anglo-Egyptisch Soedan', '39' ],
		[ 'Canada', '36' ],
		[ 'Deens Groenland', '33' ],
		[ 'Kazachstan', '27' ],
		[ 'Peru', '26' ],
		[ 'Unie van Indochina', '26' ],
		[ 'Chinese Rijk', '26' ],
		[ 'Siberië', '24' ],
		[ 'Frans Madagascar', '23' ],
		[ 'Brits Pakistan', '23' ],
		[ 'Chinees Sinkiang', '23' ],
		[ 'Brits-India', '22' ],
		[ 'Confederale Staten van Amerika', '15' ],
		[ 'Republiek Amazonas', '12' ],
		[ 'Brits Birma', '10' ],
		[ 'Ecuador', '6' ],
		[ 'Abessinië', '4' ],
		[ 'Nepal', '2' ],
		[ 'Russische Rijk', '1' ],
		[ 'Brits Kashmir', '1' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Republiek Opper Volta', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Italië', '189' ],
		[ 'Japanse rijk', '179' ],
		[ 'Frans Algerije', '152' ],
		[ 'Zweden', '134' ],
		[ 'Arabië', '118' ],
		[ 'Het Koninkrijk Engeland', '107' ],
		[ 'Duits Tanzania', '96' ],
		[ 'Verenigde Staten van Amerika', '84' ],
		[ 'Papoea Nieuw-Guinese', '82' ],
		[ 'Republiek van Australië', '73' ],
		[ 'Chili', '66' ],
		[ 'Duits Kameroen', '65' ],
		[ 'Argentinië', '51' ],
		[ 'Nederlands Oost-Indië', '49' ],
		[ 'Brits Canada', '48' ],
		[ 'Brits Egypte', '46' ],
		[ 'Canada', '41' ],
		[ 'Anglo-Egyptisch Soedan', '41' ],
		[ 'Deens Groenland', '28' ],
		[ 'Kazachstan', '28' ],
		[ 'Peru', '27' ],
		[ 'Siberië', '27' ],
		[ 'Chinese Rijk', '27' ],
		[ 'Chinees Sinkiang', '26' ],
		[ 'Frans Madagascar', '25' ],
		[ 'Unie van Indochina', '22' ],
		[ 'Brits-India', '22' ],
		[ 'Brits Pakistan', '20' ],
		[ 'Confederale Staten van Amerika', '14' ],
		[ 'Republiek Amazonas', '13' ],
		[ 'Brits Birma', '9' ],
		[ 'Ecuador', '7' ],
		[ 'Abessinië', '4' ],
		[ 'Brits Kashmir', '2' ],
		[ 'Nepal', '2' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Republiek Opper Volta', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Russische Rijk', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Italië', '199' ],
		[ 'Japanse rijk', '184' ],
		[ 'Frans Algerije', '171' ],
		[ 'Zweden', '134' ],
		[ 'Het Koninkrijk Engeland', '109' ],
		[ 'Arabië', '105' ],
		[ 'Duits Tanzania', '101' ],
		[ 'Verenigde Staten van Amerika', '88' ],
		[ 'Papoea Nieuw-Guinese', '82' ],
		[ 'Chili', '67' ],
		[ 'Republiek van Australië', '66' ],
		[ 'Duits Kameroen', '65' ],
		[ 'Nederlands Oost-Indië', '51' ],
		[ 'Brits Canada', '49' ],
		[ 'Brits Egypte', '47' ],
		[ 'Canada', '45' ],
		[ 'Argentinië', '45' ],
		[ 'Anglo-Egyptisch Soedan', '40' ],
		[ 'Frans Madagascar', '30' ],
		[ 'Peru', '27' ],
		[ 'Siberië', '27' ],
		[ 'Chinese Rijk', '27' ],
		[ 'Unie van Indochina', '26' ],
		[ 'Chinees Sinkiang', '26' ],
		[ 'Kazachstan', '26' ],
		[ 'Deens Groenland', '24' ],
		[ 'Brits-India', '22' ],
		[ 'Brits Pakistan', '19' ],
		[ 'Confederale Staten van Amerika', '13' ],
		[ 'Republiek Amazonas', '11' ],
		[ 'Brits Birma', '9' ],
		[ 'Ecuador', '7' ],
		[ 'Nepal', '2' ],
		[ 'Abessinië', '1' ],
		[ 'Brits Kashmir', '1' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Republiek Opper Volta', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Russische Rijk', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Japanse rijk', '257' ],
		[ 'Italië', '227' ],
		[ 'Frans Algerije', '188' ],
		[ 'Zweden', '143' ],
		[ 'Duits Tanzania', '143' ],
		[ 'Het Koninkrijk Engeland', '115' ],
		[ 'Verenigde Staten van Amerika', '94' ],
		[ 'Duits Kameroen', '77' ],
		[ 'Chili', '69' ],
		[ 'Papoea Nieuw-Guinese', '63' ],
		[ 'Brits Canada', '59' ],
		[ 'Brits Egypte', '54' ],
		[ 'Republiek van Australië', '53' ],
		[ 'Canada', '51' ],
		[ 'Argentinië', '49' ],
		[ 'Anglo-Egyptisch Soedan', '42' ],
		[ 'Frans Madagascar', '34' ],
		[ 'Peru', '29' ],
		[ 'Unie van Indochina', '28' ],
		[ 'Chinees Sinkiang', '27' ],
		[ 'Arabië', '24' ],
		[ 'Siberië', '24' ],
		[ 'Brits-India', '21' ],
		[ 'Chinese Rijk', '19' ],
		[ 'Brits Pakistan', '18' ],
		[ 'Deens Groenland', '16' ],
		[ 'Confederale Staten van Amerika', '13' ],
		[ 'Republiek Amazonas', '10' ],
		[ 'Brits Birma', '9' ],
		[ 'Ecuador', '6' ],
		[ 'Brits Kashmir', '2' ],
		[ 'Nepal', '2' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Abessinië', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Republiek Opper Volta', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Russische Rijk', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Kazachstan', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Oost-Indië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Japanse rijk', '306' ],
		[ 'Italië', '221' ],
		[ 'Frans Algerije', '194' ],
		[ 'Duits Tanzania', '161' ],
		[ 'Zweden', '152' ],
		[ 'Het Koninkrijk Engeland', '119' ],
		[ 'Verenigde Staten van Amerika', '98' ],
		[ 'Duits Kameroen', '72' ],
		[ 'Chili', '70' ],
		[ 'Brits Canada', '64' ],
		[ 'Canada', '55' ],
		[ 'Argentinië', '55' ],
		[ 'Anglo-Egyptisch Soedan', '44' ],
		[ 'Republiek van Australië', '39' ],
		[ 'Frans Madagascar', '35' ],
		[ 'Brits Egypte', '33' ],
		[ 'Peru', '30' ],
		[ 'Unie van Indochina', '29' ],
		[ 'Chinees Sinkiang', '28' ],
		[ 'Siberië', '28' ],
		[ 'Chinese Rijk', '28' ],
		[ 'Papoea Nieuw-Guinese', '23' ],
		[ 'Brits Pakistan', '19' ],
		[ 'Brits-India', '18' ],
		[ 'Confederale Staten van Amerika', '14' ],
		[ 'Republiek Amazonas', '9' ],
		[ 'Deens Groenland', '7' ],
		[ 'Arabië', '7' ],
		[ 'Ecuador', '6' ],
		[ 'Brits Kashmir', '2' ],
		[ 'Nepal', '2' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Abessinië', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Republiek Opper Volta', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Brits Birma', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Russische Rijk', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Kazachstan', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Oost-Indië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Japanse rijk', '289' ],
		[ 'Frans Algerije', '242' ],
		[ 'Italië', '232' ],
		[ 'Duits Tanzania', '160' ],
		[ 'Zweden', '158' ],
		[ 'Het Koninkrijk Engeland', '123' ],
		[ 'Verenigde Staten van Amerika', '101' ],
		[ 'Duits Kameroen', '74' ],
		[ 'Chili', '73' ],
		[ 'Brits Canada', '66' ],
		[ 'Argentinië', '62' ],
		[ 'Canada', '58' ],
		[ 'Frans Madagascar', '37' ],
		[ 'Republiek van Australië', '34' ],
		[ 'Anglo-Egyptisch Soedan', '31' ],
		[ 'Peru', '30' ],
		[ 'Unie van Indochina', '30' ],
		[ 'Siberië', '30' ],
		[ 'Chinese Rijk', '30' ],
		[ 'Chinees Sinkiang', '29' ],
		[ 'Brits Pakistan', '20' ],
		[ 'Confederale Staten van Amerika', '15' ],
		[ 'Papoea Nieuw-Guinese', '15' ],
		[ 'Brits-India', '14' ],
		[ 'Republiek Amazonas', '9' ],
		[ 'Ecuador', '6' ],
		[ 'Deens Groenland', '5' ],
		[ 'Brits Kashmir', '2' ],
		[ 'Nepal', '2' ],
		[ 'Arabië', '1' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Brits Egypte', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Abessinië', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Republiek Opper Volta', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Brits Birma', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Russische Rijk', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Kazachstan', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Oost-Indië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	],
	[
		[ 'Japanse rijk', '332' ],
		[ 'Italië', '270' ],
		[ 'Frans Algerije', '236' ],
		[ 'Duits Tanzania', '193' ],
		[ 'Zweden', '157' ],
		[ 'Het Koninkrijk Engeland', '118' ],
		[ 'Verenigde Staten van Amerika', '101' ],
		[ 'Duits Kameroen', '94' ],
		[ 'Chili', '64' ],
		[ 'Argentinië', '61' ],
		[ 'Canada', '57' ],
		[ 'Brits Canada', '57' ],
		[ 'Frans Madagascar', '37' ],
		[ 'Peru', '30' ],
		[ 'Siberië', '30' ],
		[ 'Unie van Indochina', '29' ],
		[ 'Chinees Sinkiang', '29' ],
		[ 'Chinese Rijk', '29' ],
		[ 'Confederale Staten van Amerika', '15' ],
		[ 'Brits-India', '10' ],
		[ 'Anglo-Egyptisch Soedan', '9' ],
		[ 'Republiek van Australië', '9' ],
		[ 'Papoea Nieuw-Guinese', '9' ],
		[ 'Republiek Amazonas', '7' ],
		[ 'Brits Pakistan', '6' ],
		[ 'Ecuador', '5' ],
		[ 'Deens Groenland', '2' ],
		[ 'Brits Kashmir', '2' ],
		[ 'Nepal', '2' ],
		[ 'Spanje', '0' ],
		[ 'Frankrijk', '0' ],
		[ 'Het Duitse Rijk', '0' ],
		[ 'Oostenrijk-Hongarije', '0' ],
		[ 'Griekenland', '0' ],
		[ 'Noorwegen', '0' ],
		[ 'Finland', '0' ],
		[ 'Schotland', '0' ],
		[ 'Ierland', '0' ],
		[ 'Wit-Russische Republiek', '0' ],
		[ 'Baffin', '0' ],
		[ 'Federale Staten van Amerika', '0' ],
		[ 'Mexico', '0' ],
		[ 'Verenigde Latijns-Amerikaanse Naties', '0' ],
		[ 'Caribische Eilandenrepubliek', '0' ],
		[ 'Venezuela', '0' ],
		[ 'Colombia', '0' ],
		[ 'Verenigde Staten van Brazilië', '0' ],
		[ 'Republiek van Argentinië', '0' ],
		[ 'Republiek van Piratini', '0' ],
		[ 'Bolivia', '0' ],
		[ 'Brits Egypte', '0' ],
		[ 'Frans West-Afrika', '0' ],
		[ 'Abessinië', '0' ],
		[ 'Unie van Zuid-Afrika', '0' ],
		[ 'Belgisch Congo', '0' ],
		[ 'Duits Namibië', '0' ],
		[ 'Portugees Mozambique', '0' ],
		[ 'Republiek Opper Volta', '0' ],
		[ 'Frans Marokko', '0' ],
		[ 'Perzië', '0' ],
		[ 'Ottomaanse Rijk', '0' ],
		[ 'Brits Birma', '0' ],
		[ 'Arabië', '0' ],
		[ 'Communistisch Rusland', '0' ],
		[ 'Russische Rijk', '0' ],
		[ 'Yakutia', '0' ],
		[ 'Archangelsk', '0' ],
		[ 'Kazachstan', '0' ],
		[ 'Mantsjoerije', '0' ],
		[ 'Republiek China', '0' ],
		[ 'Koreaanse Rijk', '0' ],
		[ 'Siam', '0' ],
		[ 'Australië', '0' ],
		[ 'Brits Australië', '0' ],
		[ 'Nederlands Oost-Indië', '0' ],
		[ 'Nederlands Indonesië', '0' ],
		[ 'Amerikaanse Filipijnen', '0' ],
		[ 'Republiek van Filipijns Moro', '0' ],
		[ 'Brits Nieuw-Zeeland', '0' ],
		[ 'Nederlands Nieuw-Guinea', '0' ]
	]
]
}

module.exports = responseExampleLong;

