[ 
	[ 
		[ 'Frankrijk', '154' ],
		[ 'Rusland', '154' ],
		[ 'Zweden', '154' ],
		[ 'Oostenrijk-Hongarije', '154' ],
		[ 'Groot-Brittanië', '144' ],
		[ 'Het Duitse Rijk', '144' ],
		[ 'Italië', '144' ],
		[ 'Het Ottomaanse Rijk', '144' ],
		[ 'Spanje', '144' ],
		[ 'Marokko', '144' ],
		[ 'Denemarken', '120' ],
		[ 'België', '72' ],
		[ 'Portugal', '72' ],
		[ 'Griekenland', '61' ],
		[ 'Roemenië', '61' ],
		[ 'Bulgarije', '49' ],
		[ 'Polen', '49' ],
		[ 'Servië', '37' ]
	],
	[
		[ 'Frankrijk', '155' ],
		[ 'Het Duitse Rijk', '152' ],
		[ 'Oostenrijk-Hongarije', '152' ],
		[ 'Het Ottomaanse Rijk', '151' ],
		[ 'Spanje', '151' ],
		[ 'Rusland', '150' ],
		[ 'Zweden', '149' ],
		[ 'Groot-Brittanië', '142' ],
		[ 'Italië', '142' ],
		[ 'Marokko', '141' ],
		[ 'Denemarken', '118' ],
		[ 'België', '72' ],
		[ 'Portugal', '71' ],
		[ 'Griekenland', '60' ],
		[ 'Roemenië', '60' ],
		[ 'Bulgarije', '49' ],
		[ 'Polen', '49' ],
		[ 'Servië', '37' ]
	],
	[
		[ 'Frankrijk', '152' ],
		[ 'Oostenrijk-Hongarije', '149' ],
		[ 'Spanje', '149' ],
		[ 'Het Duitse Rijk', '148' ],
		[ 'Groot-Brittanië', '146' ],
		[ 'Italië', '146' ],
		[ 'Rusland', '146' ],
		[ 'Het Ottomaanse Rijk', '146' ],
		[ 'Zweden', '145' ],
		[ 'Marokko', '145' ],
		[ 'Denemarken', '120' ],
		[ 'België', '74' ],
		[ 'Portugal', '71' ],
		[ 'Griekenland', '62' ],
		[ 'Roemenië', '61' ],
		[ 'Bulgarije', '50' ],
		[ 'Polen', '50' ],
		[ 'Servië', '38' ]
	],
	[
		[ 'Frankrijk', '162' ],
		[ 'Oostenrijk-Hongarije', '158' ],
		[ 'Het Ottomaanse Rijk', '154' ],
		[ 'Het Duitse Rijk', '153' ],
		[ 'Groot-Brittanië', '152' ],
		[ 'Marokko', '150' ],
		[ 'Zweden', '149' ],
		[ 'Rusland', '147' ],
		[ 'Spanje', '144' ],
		[ 'Denemarken', '123' ],
		[ 'Italië', '81' ],
		[ 'België', '79' ],
		[ 'Portugal', '75' ],
		[ 'Griekenland', '65' ],
		[ 'Roemenië', '65' ],
		[ 'Polen', '52' ],
		[ 'Bulgarije', '51' ],
		[ 'Servië', '40' ]
	],
	[
		[ 'Het Duitse Rijk', '183' ],
		[ 'Frankrijk', '174' ],
		[ 'Oostenrijk-Hongarije', '166' ],
		[ 'Het Ottomaanse Rijk', '159' ],
		[ 'Marokko', '159' ],
		[ 'Groot-Brittanië', '158' ],
		[ 'Zweden', '146' ],
		[ 'Rusland', '142' ],
		[ 'Spanje', '141' ],
		[ 'Denemarken', '131' ],
		[ 'België', '78' ],
		[ 'Griekenland', '66' ],
		[ 'Roemenië', '63' ],
		[ 'Polen', '55' ],
		[ 'Portugal', '55' ],
		[ 'Bulgarije', '48' ],
		[ 'Servië', '41' ],
		[ 'Italië', '35' ]
	],
	[
		[ 'Frankrijk', '182' ],
		[ 'Het Duitse Rijk', '181' ],
		[ 'Oostenrijk-Hongarije', '169' ],
		[ 'Het Ottomaanse Rijk', '168' ],
		[ 'Marokko', '162' ],
		[ 'Groot-Brittanië', '157' ],
		[ 'Rusland', '152' ],
		[ 'Zweden', '143' ],
		[ 'Spanje', '136' ],
		[ 'Denemarken', '135' ],
		[ 'België', '78' ],
		[ 'Polen', '64' ],
		[ 'Roemenië', '64' ],
		[ 'Griekenland', '58' ],
		[ 'Bulgarije', '51' ],
		[ 'Portugal', '51' ],
		[ 'Servië', '35' ],
		[ 'Italië', '13' ]
	],
	[
		[ 'Frankrijk', '189' ],
		[ 'Het Duitse Rijk', '181' ],
		[ 'Oostenrijk-Hongarije', '169' ],
		[ 'Marokko', '169' ],
		[ 'Het Ottomaanse Rijk', '167' ],
		[ 'Rusland', '160' ],
		[ 'Groot-Brittanië', '156' ],
		[ 'Zweden', '145' ],
		[ 'Spanje', '137' ],
		[ 'Denemarken', '131' ],
		[ 'België', '79' ],
		[ 'Roemenië', '74' ],
		[ 'Polen', '59' ],
		[ 'Griekenland', '52' ],
		[ 'Bulgarije', '50' ],
		[ 'Portugal', '45' ],
		[ 'Servië', '33' ],
		[ 'Italië', '5' ]
	],
	[
		[ 'Frankrijk', '183' ],
		[ 'Het Duitse Rijk', '175' ],
		[ 'Marokko', '175' ],
		[ 'Het Ottomaanse Rijk', '170' ],
		[ 'Oostenrijk-Hongarije', '170' ],
		[ 'Groot-Brittanië', '157' ],
		[ 'Rusland', '156' ],
		[ 'Zweden', '153' ],
		[ 'Spanje', '143' ],
		[ 'Denemarken', '128' ],
		[ 'België', '76' ],
		[ 'Roemenië', '67' ],
		[ 'Polen', '57' ],
		[ 'Griekenland', '53' ],
		[ 'Bulgarije', '52' ],
		[ 'Portugal', '47' ],
		[ 'Servië', '33' ],
		[ 'Italië', '3' ]
	],
	[
		[ 'Marokko', '188' ],
		[ 'Frankrijk', '186' ],
		[ 'Het Ottomaanse Rijk', '182' ],
		[ 'Oostenrijk-Hongarije', '176' ],
		[ 'Het Duitse Rijk', '172' ],
		[ 'Zweden', '156' ],
		[ 'Rusland', '155' ],
		[ 'Groot-Brittanië', '149' ],
		[ 'Spanje', '137' ],
		[ 'Denemarken', '125' ],
		[ 'België', '72' ],
		[ 'Roemenië', '66' ],
		[ 'Polen', '56' ],
		[ 'Griekenland', '53' ],
		[ 'Bulgarije', '50' ],
		[ 'Portugal', '50' ],
		[ 'Servië', '28' ],
		[ 'Italië', '3' ]
	],
	[
		[ 'Marokko', '210' ],
		[ 'Frankrijk', '203' ],
		[ 'Het Ottomaanse Rijk', '190' ],
		[ 'Oostenrijk-Hongarije', '184' ],
		[ 'Het Duitse Rijk', '175' ],
		[ 'Rusland', '171' ],
		[ 'Groot-Brittanië', '153' ],
		[ 'Zweden', '152' ],
		[ 'Denemarken', '105' ],
		[ 'Spanje', '104' ],
		[ 'België', '76' ],
		[ 'Griekenland', '56' ],
		[ 'Bulgarije', '52' ],
		[ 'Polen', '51' ],
		[ 'Roemenië', '48' ],
		[ 'Portugal', '44' ],
		[ 'Servië', '22' ],
		[ 'Italië', '3' ]
	],
	[
		[ 'Marokko', '212' ],
		[ 'Frankrijk', '209' ],
		[ 'Oostenrijk-Hongarije', '198' ],
		[ 'Het Duitse Rijk', '183' ],
		[ 'Rusland', '181' ],
		[ 'Het Ottomaanse Rijk', '179' ],
		[ 'Zweden', '157' ],
		[ 'Groot-Brittanië', '149' ],
		[ 'Denemarken', '101' ],
		[ 'Spanje', '88' ],
		[ 'België', '66' ],
		[ 'Roemenië', '56' ],
		[ 'Portugal', '55' ],
		[ 'Griekenland', '51' ],
		[ 'Polen', '49' ],
		[ 'Bulgarije', '42' ],
		[ 'Servië', '21' ],
		[ 'Italië', '4' ]
	]
]
